### PR TITLE
bind-dirs: Missing ro path limitation is being fixed

### PR DESCRIPTION
**Pull request by ypid**
Depends on: QubesOS/qubes-core-agent-linux#42 (merged and released)

### CODE REVIEW

**Comment by ypid** [comment]
> This should not be merged before QubesOS/qubes-core-agent-linux#42 ends up in Qubes stable version?

Mainly a suggestion. Not sure how release management is done for docs. Do as it feels appropriate :)

**Comment by andrewdavidwong** [comment]
Looks like https://github.com/QubesOS/qubes-core-agent-linux/pull/42 has been merged now. @ypid, mind resolving conflicts?

**Comment by ypid** [comment]
Done.

**Comment by andrewdavidwong** [comment]
Thank you!

**Comment by ypid** [comment]
You are welcome. Thank you too :)

**Pull request merged**
