### PR TITLE
removed gendered language

### PR DESCRIPTION
**Pull request by mfc**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
I'm open to almost any solution to gendered language *except* sacrificing subject-verb agreement.

As you've probably noticed, I typically default to feminine, rather than masculine, pronouns. The only times I don't are when using feminine pronouns would reinforce sexual stereotypes or, as in the present case, when the referent of the pronoun is being portrayed as adversarial, bad, or evil. For the most part, I aim to follow [the American Philosophical Association's Guidelines for Non-Sexist Use of Language](http://www.apaonlinecsw.org/apa-guidelines-for-non-sexist-use-of-language).

**Comment by andrewdavidwong** [comment]
What do you think of this rewrite that avoids pronouns entirely?

**Comment by mfc** [comment]
That APA resource seems a bit old-school (1986), in the sense that it avoids suggesting they/their as a gender-neutral singular pronoun. I don't know if that's what you're referring to re: subject-verb agreement, but I think it's considered a-ok nowadays.

> What do you think of this rewrite that avoids pronouns entirely?

yep looks good!

**Comment by andrewdavidwong** [comment]
It's certainly OK in casual conversation, but not in formal writing. The docs fall somewhere in between.

**Pull request merged**
