### PR TITLE
Describe additional Windows installation options - merged

### PR DESCRIPTION
**Pull request by GWeck**
merged changes in `windows-vm.md` and `windows-tools.md` from brach `GWeck1`

### CODE REVIEW

**Comment by deeplow** [comment]
Just as context, this is the continuation from https://github.com/QubesOS/qubes-doc/pull/1040. more info ([here](https://github.com/QubesOS/qubes-doc/pull/1040#issuecomment-706287634))

**Comment by GWeck** [comment]
Just fixed some typos. For me, it it ready to be merged.

**Comment by andrewdavidwong** [comment]
@GWeck: FYI, if you notice a failing Travis CI check, you can click "Details," then "View more details on Travis CI" at the bottom, then scroll all the way to the bottom of the (long) log, and it will show you what caused the failures. (I don't know why they make it so hard to find.) In this case, the relevant portion is:

```
- ./_site/doc/windows-vm/index.html
  *  linking to internal hash #xen-pv-drivers-and-qubes-windows-tools that does not exist (line 363)
     <a href="#xen-pv-drivers-and-qubes-windows-tools">below</a>
  *  linking to internal hash #xen-pv-drivers-and-qubes-windows-tools that does not exist (line 456)
     <a href="#xen-pv-drivers-and-qubes-windows-tools">Xen PV drivers and Qubes Windows Tools</a>
htmlproofer 3.16.0 | Error:  HTML-Proofer found 2 failures!
```

Would you mind fixing these broken links before we merge this?

**Comment by GWeck** [comment]
I changed the links - they were going to a piece of text that moved from one file to the other. Now the html parser seems to be content. I hope, that's it then ...

I suppose, you have to get accustomed to Travis CI, but, as you said, they don't make that easy!

**Comment by andrewdavidwong** [comment]
Willing to review again, @deeplow?

**Comment by deeplow** [comment]
> Willing to review again, @deeplow?

Review done. Approved. @andrewdavidwong 

This is basically the [PR that was merged onto GWeck's](https://github.com/GWeck/qubes-doc/pull/1/files) plus the link fixing. I don't really get why in the git history there is `@GWeck Merge pull request #1 from deeplow/gweck/patch-1` since it already branched out from there, but the content didn't seem to change.

**Comment by GWeck** [comment]
I don't understand it either - I just fxed the links.

**Comment by andrewdavidwong** [comment]
Thank you both again!

**Comment by GWeck** [comment]
@andrewdavidwong @deeplow And thank you both for your help and your patience!

**Pull request merged**
