### PR TITLE
Add Markdown convention rule about full reference links

### PR DESCRIPTION
**Pull request by tokideveloper**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
In that case, we might as well just prescribe non-reference-style links instead, right?

**Comment by tokideveloper** [comment]
You mean something like `[our website](/https://example.com/)`?

Yes, we could but I didn't want to be too restrictive. That's why I chose that rule.

Shall I add a commit that replaces my rule with a rule that prescribes non-reference-style links?

**Comment by andrewdavidwong** [comment]
Yeah, let's just recommend only non-reference-style links.

**Comment by tokideveloper** [comment]
I can adapt all reference links to our new rule. Is one big commit (in a new PR) okay?

**Comment by andrewdavidwong** [comment]
> I can adapt all reference links to our new rule. Is one big commit (in a new PR) okay?

Should be ok, I think. @marmarek, do you foresee any problems with that?

In any case, we can review the PR once it's made and see what CI says about it.

**Comment by marmarek** [comment]
> I can adapt all reference links to our new rule. Is one big commit (in a new PR) okay?

Yes, should be ok.

**Pull request merged**
