### PR TITLE
Gsoc 2021

### PR DESCRIPTION
**Pull request by marmarek**
Removed outdated projects, added some new.

### CODE REVIEW

**Comment by marmarek** [comment]
fyi @mfc

**Comment by mfc** [comment]
thanks for the update, looks good. I've also pinged [this thread](https://github.com/QubesOS/qubes-issues/issues/2417) to see if anyone wants to be a mentor on it, as I am personally interested in its development.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
I'm confused about this PR.What action is required before it should be merged? Is it waiting for review or approval by anyone?

**Comment by marmarek** [comment]
Hmm, good question. I wanted to give @mfc a chance to comment before merging, so I guess it's good to merge now.

**Pull request merged**
