### PR TITLE
Changed security archive layout for bullseye

### PR DESCRIPTION
**Pull request by SvenSemmler**
I submitted #1191 previously but then had already purged my local fork. So I was unable to change it (if there is a way I am oblivious to it). Hence I closed #1191 and opened this pull request in it's place. Sorry for that.

### CODE REVIEW

**Comment by SvenSemmler** [comment]
@adw: sorry this was the only way I knew how to change my original PR

@unman: please review this PR

**Comment by andrewdavidwong** [comment]
> I submitted #1191 previously but then had already purged my local fork. So I was unable to change it (if there is a way I am oblivious to it). 

For future reference, I think you can clone your own fork to get it back.

> sorry this was the only way I knew how to change my original PR

No worries.

**Comment by unman** [comment]
This is fine.
That pipeline failure seems odd - can it be fixed?

**Comment by andrewdavidwong** [comment]
> This is fine.
> That pipeline failure seems odd - can it be fixed?

Never seen this message before. @fepitre, has something gone wrong?

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
>  That pipeline failure seems odd - can it be fixed?

Fixed already at https://github.com/QubesOS/qubes-continuous-integration/commit/af5cb6262f797d83ac1b635363b7b9db53b7030c

**Pull request merged**
