### PR TITLE
[GSoD] Media Troubleshooting

### PR DESCRIPTION
**Pull request by PROTechThor**
I couldn't find any audio issues that were recurring or had proper solutions to add to this list. So at this point, all issues relate to video only. It may seem more apt to name this section "Video Troubleshooting", but I think "Media Troubleshooting" is more appropriate. In the future, any audio issues found will fit in here. 

**Notable sources:**

- https://www.qubes-os.org/faq/#how-do-i-play-video-files
- https://qubes-os.discourse.group/t/thinkpad-t480-gets-pretty-hot-and-battery-barely-lasts/107/7

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Don't forget to add a link to this new page somewhere.

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The content itself is fine. But please cleanup git history - see my comment in #1062.
Approved as of d8130cde2288c9fcfe2bebec48d4aa7769800477
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+UFvkACgkQ8yiUvpaE
k4rGrw/9FqU3cBsVM8ipgStcV/4+eD9e3h0kIZOREBLxbiZwly+DW2bbqUHzT6wA
hzqZ7HsvZ+cdgw6uuo2KzK+ci85/pNCoNK7W/e4800YY/NFks2sBA3a3vgAgwm3i
9wrUilmq2JiVoB1e38kJx5BxBTLCm9nM90onuBUqokNzKZwDI6zfjsCnxCWuhmje
Wzw9G7lhvaYpw31EjkMl+9hcJM2GXeb4Y7zm50ogAPRSIRB/Z6oUOThYGCSyRjbh
K6XJn6aEe+ZenUsYzQzUQrLM3CjYyhBiJx+oBAtBvh+/VGWlBJKLqDBkBmAGArQl
iCJhaT/4mX1tHJkbIK6OERvzf91cAInUGtcrkCzVeDDIvGdlrYAzmUa75aHdJO2/
KXHSd+kA7o7fDZdYd3FgmUHIB+W8n0uPXnp/l0pYlQbKhSKuR9jLkSMxVJ21HSJY
E/dW8o8PoAmQqEQXMvNfBHUWC8dFN4FhpmeCY1Wemh2LFZgBM+DAKRp/bVEiWjIe
1xkh2kdBP0C0PY5ZMZZkwGqnpkq5/7EjGCxsE/kiRy0iRNZP5H2b0zBB5hK1wyiE
6y3g8hkmol0C3PXcpJpk5fOAJkavVuB4G3ylM34JkC6i0QMU8W9dZGDweqjeaLTZ
IyPoQ/VjXVOqRPhlWeDOS98lHONrGVbgSiNsin0VAlewBJzu9y8=
=FBPS
-----END PGP SIGNATURE-----
```

**Comment by PROTechThor** [comment]
> Don't forget to add a link to this new page somewhere.

@andrewdavidwong Thanks for catching that! :)

**Comment by andrewdavidwong** [comment]
Same situation as the one I described in https://github.com/QubesOS/qubes-doc/pull/1063#issuecomment-718394551.

@PROTechThor, please try not to remove the approval commit, since then I have no way to verify which changes have occurred since Marek approved this PR (see the newly-documented procedure here: https://www.qubes-os.org/doc/doc-guidelines/#security).

**Pull request merged**
