### PR TITLE
Downgrade images to 4.0

### PR DESCRIPTION
**Pull request by hackerncoder**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
From the CI report, it looks like this PR introduces several broken links:

```
+ htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --only_4xx --url-ignore /qubes-issues/
Running ["LinkCheck", "ScriptCheck"] on ["./_site"] on *.html... 
Ran on 1034 files!
- ./_site/intro/index.html
  *  internally linking to /attachment/wiki/GettingStarted/r4.0-qubes-manager.png, which does not exist (line 419)
     <a href="/attachment/wiki/GettingStarted/r4.0-qubes-manager.png">
      <img src="/attachment/wiki/GettingStarted/r4.0-qubes-manager.png" class="center-block more-bottom" alt="Qube Manager">
    </a>
  *  internally linking to /attachment/wiki/GettingStarted/r4.0-snapshot12.png, which does not exist (line 501)
     <a href="/attachment/wiki/GettingStarted/r4.0-snapshot12.png">
      <img src="/attachment/wiki/GettingStarted/r4.0-snapshot12.png" class="center-block more-bottom" alt="Qubes desktop screenshot">
    </a>
- ./_site/screenshots/index.html
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-convert-to-trusted-pdf-1.png, which does not exist (line 344)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-convert-to-trusted-pdf-1.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-convert-to-trusted-pdf-1.png" alt="r4.0-convert-to-trusted-pdf-1.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-converting-pdf.png, which does not exist (line 344)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-converting-pdf.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-converting-pdf.png" alt="r4.0-converting-pdf.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-copy-paste.png, which does not exist (line 326)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-copy-paste.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-copy-paste.png" alt="r4.0-copy-paste.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-1.png, which does not exist (line 332)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-1.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-1.png" alt="&quot;r4.0-copy-to-other-appvm-1.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-2.png, which does not exist (line 332)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-2.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-copy-to-other-appvm-2.png" alt="r4.0-copy-to-other-appvm-3.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-manager-and-sysnet-network-prompt.png, which does not exist (line 315)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-manager-and-sysnet-network-prompt.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-manager-and-sysnet-network-prompt.png" alt="r4.0-manager-and-sysnet-network-prompt.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-manager-firewall.png, which does not exist (line 350)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-manager-firewall.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-manager-firewall.png" alt="r4.0-manager-firewall.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-1.png, which does not exist (line 338)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-1.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-1.png" alt="r4.0-open-in-dispvm-1.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-2.png, which does not exist (line 338)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-2.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-open-in-dispvm-2.png" alt="r4.0-open-in-dispvm-2.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-password-prompt.png, which does not exist (line 303)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-password-prompt.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-password-prompt.png" alt="r4.0-password-prompt.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-software-update.png, which does not exist (line 320)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-software-update.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-software-update.png" alt="r4.0-software-update.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-desktop.png, which does not exist (line 267)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-desktop.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-desktop.png" alt="r4.0-xfce-desktop.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-programmers-desktop.png, which does not exist (line 297)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-programmers-desktop.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-programmers-desktop.png" alt="r4.0-xfce-programmers-desktop.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-red-and-green-terminals.png, which does not exist (line 358)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-red-and-green-terminals.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-red-and-green-terminals.png" alt="r4.0-xfce-red-and-green-terminals.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-start-menu.png, which does not exist (line 273)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-start-menu.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-start-menu.png" alt="r4.0-xfce-start-menu.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-three-domains-at-work.png, which does not exist (line 279)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-three-domains-at-work.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-three-domains-at-work.png" alt="r4.0-xfce-three-domains-at-work.png"></a>
  *  internally linking to /attachment/wiki/QubesScreenshots/r4.0-xfce-tray-icons.png, which does not exist (line 309)
     <a href="/attachment/wiki/QubesScreenshots/r4.0-xfce-tray-icons.png"><img src="/attachment/wiki/QubesScreenshots/r4.0-xfce-tray-icons.png" alt="r4.0-xfce-tray-icons.png"></a>
/home/gitlab-runner/.gem/ruby/gems/html-proofer-3.16.0/lib/html-proofer/runner.rb:176:in `print_failed_tests': HTML-Proofer found 19 failures! (RuntimeError)
htmlproofer 3.16.0 | Error:  HTML-Proofer found 19 failures!
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.16.0/lib/html-proofer/runner.rb:51:in `run'
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.16.0/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.16.0/bin/htmlproofer:11:in `<top (required)>'
	from /home/gitlab-runner/bin/htmlproofer:23:in `load'
	from /home/gitlab-runner/bin/htmlproofer:23:in `<main>'
+ all_ok=false
Some checked failed. See above.
```

**Comment by andrewdavidwong** [comment]
Oh, maybe that's because https://github.com/QubesOS/qubes-attachment/pull/40 hadn't been merged yet. Let's try rerunning the job now that is has been.

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
@fepitre, I also tried going to [the site](https://gitlab.com/QubesOS/qubes-doc/-/pipelines/256696767) and clicking "Retry," but it said, "An error occurred while making the request."

**Comment by fepitre** [comment]
> PipelineRetry

Cannot check right now, but if it has not worked, it's because I've forgot to add you in the authorized users to perform this action. The retry in Gitlab will not work if you are not a user in QubesOS group. If you have not an account there, you can signin/login with the help of Github then we add you into the group and you will be able to retry using the web interface too.

**Comment by marmarek** [comment]
PipelineRefresh

**Comment by hackerncoder** [comment]
I tested it on my computer, no problems, so it is definitely because the other PR wasn't merged.

**Comment by andrewdavidwong** [comment]
> Cannot check right now, but if it has not worked, it's because I've forgot to add you in the authorized users to perform this action. The retry in Gitlab will not work if you are not a user in QubesOS group. If you have not an account there, you can signin/login with the help of Github then we add you into the group and you will be able to retry using the web interface too.

Ok. My GitLab username is `adw`.

**Pull request merged**
