### PR TITLE
Reformat packages into table, remove unneeded info

### PR DESCRIPTION
**Pull request by deathgrippin**
- Reformat the package listing within the Fedora section into a table, consistent with the Debian and CentOS sections
- Reformat a package name to use code style
- Remove packages mentions that are unneeded with the new table

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
IIRC, I previously re-formatted this *from* a table into a bulleted list because long, horizontal tables with lots of text are hard to maintain in Markdown and hard to use/read on the Web, since they require a lot of vertical scrolling. So, I'm skeptical about the formatting change.

**Comment by deathgrippin** [comment]
I'd be willing to do the reverse - switching the tables into a bulleted list format. It just makes more sense for them all to have the same formatting and not be mixed.

**Comment by andrewdavidwong** [comment]
> I'd be willing to do the reverse - switching the tables into a bulleted list format.

Sounds good to me.

> It just makes more sense for them all to have the same formatting and not be mixed.

Agreed.

**Comment by deathgrippin** [comment]
Okay; I'm closing this pull request then. I'll have the appropriate change ready in the next few days.

**Pull request closed without merging**
