### PR TITLE
troubleshooting: add qubes.skip_autostart

### PR DESCRIPTION
**Pull request by fepitre**
Related QubesOS/qubes-issues#4312

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by fepitre** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The content is fine. Title could use an improvement, maybe 'Skip automatic start of qubes'? otherwise it sounds like skipping starting the whole system...
Approved as of bccc64d480f96f6b03df28d7baac7d3ffbf20918
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmDV5kwACgkQ8yiUvpaE
k4poCBAAgXiBEdkxsCk6GiI0LyvBbt3jGj2uXDXFo/SPA4FDStaRXEydKopFiKes
SbLC//mC/T8hLNIqD5HkdEoBqqtn++jllr0Gj9ReZTq2UDLX3sTSwDtQgx+tSdt7
P89EvTfUbot9SI6/DaNfGT8LHgKAbiKbGVaj9M/Pol6DLbO25luGotLVfjP6QcWL
tKA1rOwpW6xnbY5TqR3UKZUtnZ9URjbTA6aH5t6N8DT4aa9OvbirmljUIFq1QevP
2uoUM0SILtomhea5sVyg9EROPQrzczs9dke1YfE2esvPALuBmBgOFuwW1TxtyEtI
XccPxTVH8nwt8rc4P0TangBrJaXSO0e9eFkAc9TI3OiZOAb4OBLAK4pdAExwKELQ
BcrRpqgJ5kruENyy+gXExcHlc4kqNPlTz1/kIo8uUE3FCYlMIJxxQboxf95P3VqT
4+gjRtsSl2eh6AgHBovLW943c/PAVESnYTGb+yBxCi1+iteEeQjOZLugRwPH5sf/
SuoSE1rYjcxoPxtSodQFQzlgDuZLvpCVc7SrVu4D34Jcxlox9lwVH1MnblI/5eLP
/vdDs4AgYGmTteQfQ0nyjlrvSPwROqwkPq2M1eHgiyizxJx5k8ayVh0GHsdqJUSk
eGgjJyaBptfcqPuJIS56xFSqq6y/BN7aYdTjLo7ZzoytxLBQm9Q=
=CvNY
-----END PGP SIGNATURE-----
```

**Comment by fepitre** [comment]
Maybe I should let @andrewdavidwong rephrase the title and not commit anymore?

**Comment by andrewdavidwong** [comment]
> Maybe I should let @andrewdavidwong rephrase the title and not commit anymore?

Changing the title is still ok, but I can take care of it, if you prefer.

**Pull request merged**
