### PR TITLE
Updated doc.md to include link to Multimedia Howto

### PR DESCRIPTION
**Pull request by praschdorff**
The howto configuration/multimedia describes how to setup a debian based multimedia AppVM which can be used for Netflix, Amazon Prime, Spotify and to playback DVDs

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Why not include this in #418?

**Comment by praschdorff** [comment]
Hello Andrew,

> Why not include this in #418
<https://github.com/QubesOS/qubes-doc/pull/418>?

Happy to do so, but I am a GIT newbie, I have git cloned  the qubes-doc
repository to my local laptop, changed the files but when I try to upload
them I get an Error:

"remote: Permission to QubesOS/qubes-doc.git denied to praschdorff"

I think that I am uploading to the main repository, the problem is, that I
am missing some git knowledge.

A short howto about how to contribute to the documentation would be great.

Thereof I have copy and pasted the content of my two changed files...
doc.md and configuration/multimedia.md into my GitHUB fork of qubes-doc.

I don't know of this is the right way... Hope so.

- Philipp


Am 18.02.2018 11:43 nachm. schrieb "Andrew David Wong" <
notifications@github.com>:

Why not include this in #418 <https://github.com/QubesOS/qubes-doc/pull/418>
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/QubesOS/qubes-doc/pull/594#issuecomment-366554949>, or mute
the thread

**Comment by praschdorff** [comment]
On 02/18 03:21, Andrew David Wong wrote:

> We have this, if you haven't already seen it: 
> https://www.qubes-os.org/doc/doc-guidelines/

I know this, but I like to use the terminal.
The missing part was that I didn't upload my SSH key to GitHub.
I have now a local repository which I can sync with the qubes-doc master.
I have added a short notice about where to find the documentation to verifiy the Google Chrome packages but I didn't want to create a 3rd Pull request from the terminal.
Can we merge the two existing pull requests for 1) doc.md and 2) configuration/multimedia.md ?

P.

**Comment by andrewdavidwong** [comment]
> Can we merge the two existing pull requests for 1) doc.md and 2) configuration/multimedia.md ?

No, but you should be able to push your commits to the other PR, or just add a commit to the other PR with this same one small change.

**Comment by praschdorff** [comment]
Edited page to remove existing conflict and to include merge 418 in the doc index page.

**Comment by andrewdavidwong** [comment]
Forgot about this. Already done: https://github.com/QubesOS/qubes-doc/commit/6a176d61ccd22d4d87786a5e00b5a19d1488127f.

**Pull request closed without merging**
