### PR TITLE
working instructions to create a Kali VM template

### PR DESCRIPTION
**Pull request by lorenzog**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@lorenzog: Thank you for contributing this. Please resolve any conflicts, then let me know when you're ready to have this merged.

**Comment by lorenzog** [comment]
My apologies, my fork was out of date and there were lots of conflicts. I think I fixed them.

**Comment by andrewdavidwong** [comment]
I'm a bit confused. We already have a Kali page at `/doc/pentesting/kali/`, but your PR doesn't propose to edit or replace that page. Instead, it creates a new page at `/doc/kali/`. We definitely don't want to have two distinct Kali pages. Care to explain?

**Comment by lorenzog** [comment]
@andrewdavidwong I'm also confused now. I had forked the original repo a while ago when I first tried to make Kali work. When I synchronised it I noticed the kali page in its original location was gone and I thought it had been deleted completely; I did not investigate and assumed there was no Kali page any more.

I'll merge it and re-submit...

**Comment by andrewdavidwong** [comment]
Ok, thanks!

**Comment by andrewdavidwong** [comment]
By the way, @Jeeppler, since you wrote the existing Kali page, please let me know if you have any serious objections to the edits @lorenzog is proposing to make. I would rather we not get bogged down in an argument over minutiae, but at the same time, I want to respect each community member's contribution.

**Comment by lorenzog** [comment]
@andrewdavidwong I've merged my changes with the previous `kali` page. 

Summary:

Before 3.2, installing kali involved manually editing the sources of the Debian template. The alternative method was to use the `katoolin` script, which was documented by @Jeeppler. The old page contained both methods but they were mixed together as most step were identical.

In my new version I've kept  @Jeeppler contribution untouched (except for an indentation and for the links' style) when it related to the use of `katoolin`. I've removed the bits that detailed the old manual steps as they were broken and resulted in a non-booting template - as discussed in https://github.com/QubesOS/qubes-issues/issues/1981. 

I've then updated and corrected the 'manual' steps and put them in a separate section at the bottom of the document, to avoid any conflicts with @Jeeppler contribution and with previous stuff.

**Comment by andrewdavidwong** [comment]
Thanks for all your hard work, @lorenzog!

**Pull request merged**
