### PR TITLE
Kali Linux TemplateVM

### PR DESCRIPTION
**Pull request by ppiotr3k**
Partial rewrite of the page, mainly the last Kali TemplateVM section to:
- add missing steps in TemplateVM creation (ex: trimming to optimize disk space usage)
- correct inconsistent file names across subsections, which made the instruction nonfunctional "as-it"
- match shell commands with textual instructions
- remove unused, duplicate or wrongly formatted links /references
- enhance consistency in commands and style used within the same section
- enhance consistency in commands and style with other pages (ex: Qubes' Basics and Common Tasks, Fedora 23 to Fedora 24 upgrade, etc.)
- better follow Qubes Glossary and Documentation Guidelines
- have a hierarchical succession of headers / section titles

### CODE REVIEW

**Comment by ppiotr3k** [comment]
TODO: instructions about upgrading Debian 8.0 to Debian 9.0 should be moved from this page to the Debian TemplateVM page directly, and linking to the Debian page instead.

**Comment by andrewdavidwong** [comment]
@Jeeppler, would you be willing to review this PR?

**Comment by Jeeppler** [comment]
For whatever reason, I am unable to use the 'Review' functionality of GitHub. Therefore, I will provide my feedback here.

I like the changes, those changes are a huge improvement.

**Comment by Jeeppler** [comment]
Please keep in mind that Debian 9.0 was not officially released at the time the document was written. Now, that Debian 9.0 is released we could simplify the instructions and remove the steps related to upgrading the Debian Template from 8.0 to 9.0.

**Comment by andrewdavidwong** [comment]
Thank you for your contribution, @ppiotr3k. We apologize for the long delay before merging.

Thank you for your review, @Jeeppler. As you suggested, I removed the section on upgrading a template from Debian 8 to 9.

**Comment by ppiotr3k** [comment]
Thank you @andrewdavidwong ! Totally agree on the _Debian 8 to 9_ section removal, not needed anymore nowadays. I'll push an additionnal correction to remove a small remaining reference to Debian 8 left in the merged commit.

**Pull request merged**
