### PR TITLE
add certified-laptops page

### PR DESCRIPTION
**Pull request by mfc**
adding certified laptop page

### CODE REVIEW

**Comment by mfc** [comment]
https://github.com/QubesOS/qubes-doc/blob/master/doc.md will need to be updated to link to this page

**Comment by axon-qubes** [comment]
In the future, please feel free to include the relevant change to the ToC in your pull request.

**Comment by mfc** [comment]
definitely, I wasn't sure how to link to it (/hardware/certified-laptops/ vs /certified-laptops/ etc)

**Comment by axon-qubes** [comment]
In that case, you did the right thing. :)

**Pull request merged**
