### PR TITLE
un-abbreviated title, made generic example

### PR DESCRIPTION
**Pull request by mfc**
content itself is still a mess, with "Disposable VM", "DispVM", and "DVM" all used. At some point we should probably agree on an abbreviation and propagate it.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
I think you may have missed this: https://github.com/QubesOS/qubes-issues/issues/2486#issuecomment-279191179

The usage of "DVM Template" there is intentional and should **not** be reverted.

Please see the glossary:
https://www.qubes-os.org/doc/glossary/#dispvm
https://www.qubes-os.org/doc/glossary/#dvm
https://www.qubes-os.org/doc/glossary/#dvm-template

**Comment by mfc** [comment]
missed that discussion, thanks. so it sounds like don't merge that one section title change?

**Comment by andrewdavidwong** [comment]
Yes, please add a new commit to undo that part.

**Comment by mfc** [comment]
fixed version: https://github.com/QubesOS/qubes-doc/pull/285

**Pull request closed without merging**
