### PR TITLE
templates.md: add persistence table

### PR DESCRIPTION
**Pull request by awokd**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Would you mind formatting the source a bit more nicely?

**Comment by andrewdavidwong** [comment]
Thanks. :smiley_cat:

**Comment by awokd** [comment]
I think so; will try. Is it the merges that are the problem or the other misc. ones? Running a merge every week was the only way I could figure out to keep our branch up to date.

**Comment by marmarek** [comment]
Both merges and others. See here: https://help.github.com/articles/github-flow/

**Comment by awokd** [comment]
Sure, that's the flow I follow for personal commits but for Qubes Community ones we've been maintaining a semi-permanent fork of qubes-doc: https://github.com/Qubes-Community. I suppose my merge script could instead delete our repo and recreate it every week as long as we don't have something in progress on it. I'll do that anyways to clean this one up.

**Pull request closed without merging**
