### PR TITLE
Update verifying-signatures.md

### PR DESCRIPTION
**Pull request by dan-mi-sun**
Adding missing aspect to command for verifying iso image

### CODE REVIEW

**Comment by woju** [comment]
On Mon, Jan 18, 2016 at 10:55:14PM -0800, Dan Hassan wrote:
> Adding missing aspect to command for verifying iso image
> You can view, comment on, or merge this pull request online at:

If the filename of the checked file is same as signature save for .gpg
or .asc, there is no need to put it again on the command line.

-- 
regards,                        _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>

**Comment by dan-mi-sun** [comment]
Although this is true, being explicit means more cases will be caught?

I guess as long as people have got the gist, then they can always RTFM for GPG :)

**Comment by axon-qubes** [comment]
> Although this is true, being explicit means more cases will be caught?

I'm not sure what you mean. More cases of what?

> I guess as long as people have got the gist, then they can always RTFM for GPG :)

Again, I'm not sure what you mean. What does RTFMing for GPG have to do with the fact that GPG assumes the second argument?

**Comment by dan-mi-sun** [comment]
More of an edge case. Was helping a friend who had downloaded the .asc and the .iso to two different locations.

Leaving the explicit command and relying on the software assumption left them not sure what they had left out...

In this case it would simply have required them to read the GPG documentation :)

**Comment by axon-qubes** [comment]
So, this depends highly on the user's level of understanding, right? A user who fails to understand why the file isn't verifying when the file and the sig are in different directories could also easily fail to understand what this means:

    $ gpg -v --verify Qubes-R2-x86_64-DVD.iso.asc Qubes-R2-x86_64-DVD.iso 

In particular, they may easily fail to understand that the first argument specifies the sig, while the second argument specifies the file to be verified.

**Comment by dan-mi-sun** [comment]
True.

Would be happy to send across a PR with some more explicit explanations.

**Comment by dan-mi-sun** [comment]
Though understandably it can be a rabbit hole if trying to account for all possible skill levels.

**Comment by axon-qubes** [comment]
Yes, exactly. Our goal here is to help (prospective) Qubes users properly verify the Qubes ISOs they download, not to teach them how GPG works. Of course, teaching people how GPG works and how to properly use it is a worthy goal; it's just not what this particular page is meant for.

**Comment by marmarek** [comment]
As [HW42 said](https://groups.google.com/d/msgid/qubes-devel/56A403D6.10706%40ipsumj.de), it may be good idea to include this change anyway:
From man gpg:

> Note: If the option --batch is not used, gpg may assume that a single
> argument is a file with a detached signature and it will try to find a
> matching data file by stripping certain suffixes.  Using this historical
> feature to verify a detached  signature is strongly discouraged; always
> specify the data file too.

**Comment by axon-qubes** [comment]
Ah, good call. I missed those replies from the other thread. Merging.

**Pull request merged**
