### PR TITLE
Fixed erreneous documentation in Split gpg

### PR DESCRIPTION
**Pull request by vrushti-mody**
Fixes Issue #4901 'Outdated paragraph in Split GPG limitations section'

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Some notes:
 - You must include `QubesOS/qubes-issues` before the issue number for it to link and auto-close on merge
 - `information.)Note:` <-- missing space
 - `**donot**` <-- should be two words
 - `let` --> `lets`
 - `cube` --> `qube`

**Comment by vrushti-mody** [comment]
> Some notes:
> 
> * You must include `QubesOS/qubes-issues` before the issue number for it to link and auto-close on merge
> * `information.)Note:` <-- missing space
> * `**donot**` <-- should be two words
> * `let` --> `lets`
> * `cube` --> `qube`
> * The imperative mood is preferred in the commit subject line (i.e., "Fix" rather than Fixed")

I have made the changes

**Comment by andrewdavidwong** [comment]
Thank you. I'm still confused by this sentence (which is a comma splice, btw):
> The Split GPG client lets you use password-protected keys, the vault qube will show a passphrase if you are using R4. 

The first half makes sense to me, but I'm not sure how to interpret the second half. Are you saying that no passphrase will be visible on 3.2, but the passphrase will be visible on 4.0 or higher? If so, then we can just drop the mention of the version, since we no longer support documentation for 3.2.

**Comment by vrushti-mody** [comment]
> Thank you. I'm still confused by this sentence (which is a comma splice, btw):
> 
> > The Split GPG client lets you use password-protected keys, the vault qube will show a passphrase if you are using R4.
> 
> The first half makes sense to me, but I'm not sure how to interpret the second half. Are you saying that no passphrase will be visible on 3.2, but the passphrase will be visible on 4.0 or higher? If so, then we can just drop the mention of the version, since we no longer support documentation for 3.2.

I will remove the version. The sentence will be changed to: 'The Split GPG client lets you use password-protected keys and the vault qube will show the passphrase.'

**Comment by andrewdavidwong** [comment]
After reviewing the whole context, I'm not sure this addition makes sense. We just finished telling the reader not to use a passphrase on their key. Why are we now telling them, "The Split GPG client lets you use password-protected keys and the vault qube will show the passphrase." And what does "show the passphrase" mean?

**Comment by vrushti-mody** [comment]
> After reviewing the whole context, I'm not sure this addition makes sense. We just finished telling the reader not to use a passphrase on their key. Why are we now telling them, "The Split GPG client lets you use password-protected keys and the vault qube will show the passphrase." And what does "show the passphrase" mean?

I think that the sentence should be eliminated all together since the passphrase doesn't show specially in the latest version. I only added it because the person who made the previous pull request wrote it.

**Comment by andrewdavidwong** [comment]
I'm confused as to why there now appears to be merge conflict data in the text.

**Comment by vrushti-mody** [comment]
I'm unsure too. I'll add a merge request again. Can't figure out the reason though

**Comment by vrushti-mody** [comment]
> I'm confused as to why there now appears to be merge conflict data in the text.

I'm unsure too. I'll add a merge request again. Can't figure out the reason though

**Pull request merged**
