### PR TITLE
shortcut configuration via qvm-features instead of guid.conf

### PR DESCRIPTION
**Pull request by mdik**
With Qubes 4.1 coming out soon, maybe it's a good time to tell people how to get their shortcuts working again?

### CODE REVIEW

**Comment by unman** [comment]
On Thu, Oct 14, 2021 at 06:39:18AM -0700, Andrew David Wong wrote:
> Alternatively, we can just refrain from merging this PR (and others like it) until either we've set up release-specific docs or 4.1 has been released.
> 

Yes, it's confusing all round otherwise.

**Comment by marmarek** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

This should land for R4.1 documentation only; if we'll have common docs for R4.0 and R4.1, then this needs two sections
Approved as of 9f1c4aa79abce4029023de88cb8e143cbb285e35
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmHBzZUACgkQ8yiUvpaE
k4rDeQ//fTCy4YY8Spo6RaAnK/PvMFhIt+Zz8jtLTg/ImBNUoxHX9hisrkD6ZR4m
ycdJqnzUMXCIbFD3oSulU63PtDiQWFYKECcRbsCCa5GMmVWRS1k1o5OQ8Ro/DIYI
j1qpkdYUWXOs23wEOQWwk967o7f9d+JcAgdAMXcc4NgbG54eOoI54hwrGfuUi0KH
QqiSn4EZAz1VLm7UBv3xr86wnze4kq+O94yTAUpXwIKDbMMzdsdUyr5UsG1qCIJp
WBBNxSDFQAOk3oYIscbpHk/jH2hzPld3s2DMFVPOJqRk6jqkNHF5f4KP9MyuI1IG
eJR8bGanUSgd8u/zc7F+MHPBAemmTdB92L70NBxraH0eMCSSRmxzxK4+3pBCtDkT
29lLL8J9NPyCq1giKn8jeTwal9xSeFk7ZuVZpbSOeKmNvrzoLJayytkI+YSWt9Ov
rtkEtPZ3ygTimKLNyZnv1/ESYgUW12lmbrj6uBfr0vkhVKVyqMBdiWDNWgT8Bhd4
nlcCrfGXyWMKNuVeLAWwxKwJT8wzhX8A3ux7TjDRoBT6Al0uqv1m/G2gtZe8LYfC
Gj9IvH+k3wFIzEiXoIYw9CTVGmVew++hqEBZigbLVgNQUsc+r1p6F6neobijFKls
kzodIp6dEeE7/N3b2gE//jcRTaxZGrByv8JDed8OAhoQGKdE6DU=
=SdwA
-----END PGP SIGNATURE-----
```

**Comment by andrewdavidwong** [comment]
> This is accurate for R4.1, but this way we loose info how to change it on R4.0. Please add separate section according to https://www.qubes-os.org/doc/documentation-style-guide/#release-specific-documentation

Actually, Marek was right. I forgot that there is now a six-month period where 4.0 and 4.1 are both supported, so we can't replace 4.0 documentation even though 4.1 is now out. @mdik, could you please follow [this](https://www.qubes-os.org/doc/documentation-style-guide/#release-specific-documentation) as Marek asked? (Once 4.0 reaches EOL, the current version will be good, so if nothing happens in the next six months, this can be merged as-is.)

**Comment by mdik** [comment]
As these config steps are something people usually do after a fresh install, and virtually all fresh installs will be 4.1, is it really worth the effort to list both?

**Comment by andrewdavidwong** [comment]
> (Once 4.0 reaches EOL, the current version will be good, so if nothing happens in the next six months, this can be merged as-is.)

Since it has now been almost five months, I think it's fine to merge this as-is.

**Pull request merged**
