### PR TITLE
Insignificantly edit martus.md

### PR DESCRIPTION
**Pull request by stubbybubby**
Modified the list heading to be grammatically consistent.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Is the existing list heading really grammatically inconsistent?

**Comment by stubbybubby** [comment]
Actually this would be the correct phrasing:

**Comment by stubbybubby** [comment]
http://www.whitesmoke.com/punctuation-colon.html

**Comment by stubbybubby** [comment]
You can leave it as is if you don't care about following those rules, but I would still change it to the "To install martus" phrasing if I were you. I just like it more.

**Comment by andrewdavidwong** [comment]
Ok, merged the first version: https://github.com/QubesOS/qubes-doc/commit/36eb4058e4c048603d199edcdf2589e9661e3179

**Pull request closed without merging**
