### PR TITLE
next steps: adding an icon

### PR DESCRIPTION
**Pull request by deeplow**
The next step after installing an application is generally adding an icon to the AppVM, so it may be good to refer this as a next step here. 

Possibly what originated confusion with [this user on the forum](https://qubes-os.discourse.group/t/issues-installing-transmission/1315)

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
This should happen automatically. No manual step should be necessary. If there is some bug preventing this from working correctly, please file a bug report instead.

**Comment by marmarek** [comment]
I think @deeplow meant going to appropriate VM settings "Applications" tab and actually selecting the application to be included in the menu. That doesn't happen automatically when you install new application,

**Comment by deeplow** [comment]
> I think @deeplow meant going to appropriate VM settings "Applications" tab and actually selecting the application to be included in the menu. That doesn't happen automatically when you install new application,

Thanks. This is it @marmarek. Sorry for the confusion @andrewdavidwong

**Comment by andrewdavidwong** [comment]
I think that this way of writing it is a bit too confusing. It makes it sound like some more complex manual step than what it is. Will close from separate commit.

**Comment by andrewdavidwong** [comment]
Also, the "Managing shortcuts to applications in AppVMs" page is really about troubleshooting this process. It normally shouldn't be required, so it doesn't really belong under "Common Tasks."

**Comment by deeplow** [comment]
> I think that this way of writing it is a bit too confusing. It makes it sound like some more complex manual step than what it is. Will close from separate commit.

Ok. No problem

**Pull request closed without merging**
