### PR TITLE
[GSoD] Intel Troubleshooting

### PR DESCRIPTION
**Pull request by PROTechThor**
Didn't change much here. Just moved the file to "External" and modified a heading

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
I noticed we no longer have automated Travis CI checks here. Is that expected, @marmarek?

**Comment by marmarek** [comment]
Sort of - we are hit by [Travis-CI new limits](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). I've already requested increase, but haven't got response yet.

**Review by marmarek — APPROVED** [review]
Generally looks good, but lets wait for Travis to work again before merging.

**Comment by marmarek** [comment]
We have gitlab-ci almost ready. For this PR test is [here](https://gitlab.com/QubesOS/qubes-doc/-/jobs/850554356). Links are good, but spellchecker found few typos:
```
The following new unknown spellings were introduced:
    +Invisib
    +Z12
    +tha
```

**Comment by marmarek** [comment]
That's weird, those typos are not part of what you've changed. Possibly some (yet another) issue with our new gitlab pipelines... @fepitre

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by PROTechThor** [comment]
CI says a check has failed, but when I visit https://gitlab.com/QubesOS/qubes-doc/-/pipelines/221118750/failures , I don't see anything relevant :/

**Comment by andrewdavidwong** [comment]
There actually is an htmlproofer failure in the [log](https://gitlab.com/QubesOS/qubes-doc/-/jobs/872047523), but it doesn't appear to be from this PR's changes. It might be an error in CI somehow.

```
+ htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --only_4xx --url-ignore /qubes-issues/
Running ["ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 
Ran on 989 files!
- ./_site/qsp/index.html
  *  linking to internal hash #generating-and-submitting-new-report that does not exist (line 416)
     <a href="/doc/hcl/#generating-and-submitting-new-report">generating and submitting a Hardware
Compatibility List (HCL) report</a>
htmlproofer 3.17.2 | Error:  HTML-Proofer found 1 failure!
/home/gitlab-runner/.gem/ruby/gems/html-proofer-3.17.2/lib/html-proofer/runner.rb:214:in `print_failed_tests': HTML-Proofer found 1 failure! (RuntimeError)
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.17.2/lib/html-proofer/runner.rb:56:in `run'
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.17.2/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/gitlab-runner/.gem/ruby/gems/html-proofer-3.17.2/bin/htmlproofer:11:in `<top (required)>'
	from /home/gitlab-runner/bin/htmlproofer:23:in `load'
	from /home/gitlab-runner/bin/htmlproofer:23:in `<main>'
+ all_ok=false
+ false
+ echo 'Some checked failed. See above.'
+ exit 1
Some checked failed. See above.
```

**Comment by marmarek** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
I believe I'm just waiting for a signed approved from @marmarek before merging this.

**Comment by andrewdavidwong** [comment]
Oh, never mind. Looks like this is external documentation with just a minor change.

**Pull request merged**
