### PR TITLE
Custom screenlocker guide

### PR DESCRIPTION
**Pull request by 3hhh**
Should make it easier to address https://github.com/QubesOS/qubes-issues/issues/1917

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
We're in the middle of transitioning all external docs out of `qubes-doc` (see https://github.com/QubesOS/qubes-issues/issues/4693), so we ask that you please hang onto this PR until the transition is complete, then submit it over at https://github.com/Qubes-Community/. Thank you for your understanding.

**Comment by andrewdavidwong** [comment]
@3hhh: Actually, now that I think about it, you may not need to wait for anything before adding this over at https://github.com/Qubes-Community/. @awokd, does that sound right?

**Comment by 3hhh** [comment]
No worries, it [has already happened](https://github.com/Qubes-Community/Contents/pull/98).

**Comment by awokd** [comment]
>@awokd, does that sound right?
Added.

**Pull request closed without merging**
