### PR TITLE
update Windows Tools for R3

### PR DESCRIPTION
**Pull request by omeg**
Not sure if this is not breaking links (some files renamed).

### CODE REVIEW

**Comment by marmarek** [comment]
On Wed, Jul 01, 2015 at 05:13:36AM -0700, Rafał Wojdyła wrote:
> Not sure if this is not breaking links (some files renamed).

Yes, it will break some links. Add additional redirect_from header.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Regarding a note about VNC server - it should be clear that it applies
only for testing/experimental builds. In production system it is bad
idea to expose VNC server...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by omeg** [comment]
On 2015-07-01 14:54, Marek Marczykowski-Górecki wrote:
> On Wed, Jul 01, 2015 at 05:13:36AM -0700, Rafał Wojdyła wrote:
>> Not sure if this is not breaking links (some files renamed).
> 
> Yes, it will break some links. Add additional redirect_from header.
> 
WindowsTools3.md has redirect_from: /wiki/WindowsTools/, is there
something else needed?

-- 
Rafał Wojdyła
Qubes Tools for Windows developer
https://www.qubes-os.org/

**Comment by omeg** [comment]
On 2015-07-01 15:05, Marek Marczykowski-Górecki wrote:
> Regarding a note about VNC server - it should be clear that it applies
> only for testing/experimental builds. In production system it is bad
> idea to expose VNC server...
> 
True, I'll note that.

-- 
Rafał Wojdyła
Qubes Tools for Windows developer
https://www.qubes-os.org/

**Comment by marmarek** [comment]
On Wed, Jul 01, 2015 at 06:11:03AM -0700, Rafał Wojdyła wrote:
> On 2015-07-01 14:54, Marek Marczykowski-Górecki wrote:
> > On Wed, Jul 01, 2015 at 05:13:36AM -0700, Rafał Wojdyła wrote:
> >> Not sure if this is not breaking links (some files renamed).
> > 
> > Yes, it will break some links. Add additional redirect_from header.
> > 
> WindowsTools3.md has redirect_from: /wiki/WindowsTools/, is there
> something else needed?

Yes, the same also for /doc/WindowsTools/

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by omeg** [comment]
On 2015-07-01 15:21, Marek Marczykowski-Górecki wrote:
> On Wed, Jul 01, 2015 at 06:11:03AM -0700, Rafał Wojdyła wrote:
>> On 2015-07-01 14:54, Marek Marczykowski-Górecki wrote:
>> > On Wed, Jul 01, 2015 at 05:13:36AM -0700, Rafał Wojdyła wrote:
>> >> Not sure if this is not breaking links (some files renamed).
>> >
>> > Yes, it will break some links. Add additional redirect_from header.
>> >
>> WindowsTools3.md has redirect_from: /wiki/WindowsTools/, is there
>> something else needed?
> 
> Yes, the same also for /doc/WindowsTools/
> 
Done.

-- 
Rafał Wojdyła
Qubes Tools for Windows developer
https://www.qubes-os.org/

**Pull request merged**
