### PR TITLE
mention qubes updater

### PR DESCRIPTION
**Pull request by deeplow**
Although mentioned in the [getting started](https://www.qubes-os.org/doc/getting-started/#gui-and-command-line-tools), I feel like a mention of Qubes Update should absolutely also be in this page. The previous explanation was too technical / dense for people just simply wanting to update the system.

@andrewdavidwong I hope you don't mind the low-effort contribution (already spent too much time one the forum today).

This needs to be further developed (at least adding an image). If you agree with the change, could you complete it?

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
I don't have any way to take a good screenshot for this right now, but maybe @hackerncoder does.

I disagree with moving the existing content into a "Updating the system for advanced users" subsection. The Qubes Update tool is the recommended way to accomplish these steps, not something separate.

**Comment by deeplow** [comment]
> I disagree with moving the existing content into an "Updating the system for advanced users" subsection. The Qubes Update tool is the recommended way to accomplish these steps, not something separate.

My reasoning for the proposal was to make the "Qubes updater" very visibly mentioned on this page (which I think currently is not mentioned). They way, new users only really need to look at a small section at the top of this docs page. Curious users can look at what goes on behind the scenes & more advanced stuff. That was just my goal with the move. But it may be called something else.

**Comment by andrewdavidwong** [comment]
> My reasoning for the proposal was to make the "Qubes Update" very visibly mentioned on this page (which I think currently isn't, if I'm not mistaken). They way, new users only really need to look at a small section at the top of this docs page.

This part is fine.

> When going down on the page they would see "advanced" and think "ok that is not for me". 

Sort of. You actually do have to update all three parts in order to fully update Qubes, so it's still "for everyone." The Qubes Update tool just happens to be able to do all three parts for you at the same time (not sure about StandaloneVMs, though). This was probably just written before the Qubes Update tool became the main update method.

> Curious users can always look at what goes on behind the scenes & more advanced stuff.

That sounds more like developer documentation, whereas this page is actually simple end-user documentation (even in its current state).

**Comment by deeplow** [comment]
@andrewdavidwong did you merge this by mistake? It was still missing at least an image (I should have marked it as "draft")

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong did you merge this by mistake? It was still missing at least an image (I should have marked it as "draft")
> 

No, it was intentional. See the revised text I committed. It's fine to add an image, as well, but I think it's optional.

**Comment by deeplow** [comment]
I see! I was just confused because you had made a commit outside of this branch and so I thought it had gone to the docs with the `[ add image here ]`. But I see you made a commit after outside of this: https://github.com/QubesOS/qubes-doc/commit/b8d1b4ceea9a14ab52d675c0ceb9ce9abc80fbb5.

Thanks for the clarification!

**Comment by hackerncoder** [comment]
There is a actually a screenshot containing it: https://github.com/QubesOS/qubes-attachment/blob/master/wiki/QubesScreenshots/r4.0-software-update.png

**Comment by andrewdavidwong** [comment]
> I see! I was just confused because you had made a commit outside of this branch and so I thought it had gone to the docs with the `[ add image here ]`. But I see you made a commit after outside of this: [b8d1b4c](https://github.com/QubesOS/qubes-doc/commit/b8d1b4ceea9a14ab52d675c0ceb9ce9abc80fbb5).
> 
> Thanks for the clarification!

No, I made that commit inside of your branch; I just didn't push it to this PR. (I made the commit in your branch, then merged your branch.)

-----

> There is a actually a screenshot containing it: https://github.com/QubesOS/qubes-attachment/blob/master/wiki/QubesScreenshots/r4.0-software-update.png

Thanks! I've added this image to the page.

**Comment by deeplow** [comment]
@andrewdavidwong I was thinking of more along the lines of:

updates

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I was thinking of more along the lines of:
> 
> updates

Added.

**Pull request merged**
