### PR TITLE
add advice on choosing hardware

### PR DESCRIPTION
**Pull request by deeplow**
Stab at fixing https://github.com/QubesOS/qubes-issues/issues/6638

@SvenSemmler your input here is welcome if you have the bandwidth.

### CODE REVIEW

**Review by SvenSemmler — CHANGES_REQUESTED** [review]
"does not guarantee qubes will on it" ... there is a "run" or "function" missing.

**Review by SvenSemmler — CHANGES_REQUESTED** [review]
bellow:  hollow, loud, animal cry, as a bull or cow
below: lower in place, rank or value

;-) ... I used to make that mistake for years (German native speaker)

**Comment by SvenSemmler** [comment]
Other than the typos, I think this is a good change. Thanks for doing this @deeplow !

**Comment by deeplow** [comment]
@SvenSemmler thanks for taking a look. Oh my gawd these typos :sweat_smile:

I've also noticed basically the exact same text is in the notice at the top of the page. And it has been there for 4+ years... How did I not notice?!

So I've changed it to add the only missing thing. But I'm not sure this change still makes sense if it's just to add that tiny bit of info.

**Review by SvenSemmler — APPROVED** [review]
Very nice!

**Comment by andrewdavidwong** [comment]
- "The advice at the top of the page" is a bit vague and unnecessary
 - This is going to come across to non-Linux-familiar people as weird advice without further explanation, and I'm not sure that further explanation is warranted here. Linux people generally already know that compatibility is better on devices that are at least a couple years old.

Might be better just to add your advice to this doc and link to it: https://github.com/Qubes-Community/Contents/blob/master/docs/hardware/hardware-selection.md

**Pull request closed without merging**
