### PR TITLE
Added page on pptp connections

### PR DESCRIPTION
**Pull request by chandrashritii**
This PR will add a page on using PPTP connections in Qubes. Fixes [#5671](https://github.com/QubesOS/qubes-issues/issues/5671) (qubes-issues repo)

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
After seeing this PR, I wonder if we should move this to https://github.com/Qubes-Community

What do you think, @marmarek and @awokd?

**Comment by minic0m** [comment]
@chandrashritii did you test it?
Need ultimate working configuration like a openvpn in Qubes 4.0 (qubes-contrib, qubes-tunnel).
User must enter `username`, `password` and 'gateway` to establish connection.
I think that iptables rules is not full (network-manager can't establish connection on proxy-vm)

**Comment by chandrashritii** [comment]
@minic0m 
> 
> 
> @chandrashritii did you test it?

I haven't tested it but I have referred to reliable sources, including previously documented issues on the same topic.
For the firewall configuration, I referred to a previously asked user issue, answered by @unman, which can be found [here.](https://www.mail-archive.com/qubes-users@googlegroups.com/msg12279.html)
For installing the PPTP client, I referred to the [PPTP Client documentation](http://pptpclient.sourceforge.net/) and also to the documentation of individual operating systems, such as -
- [Whonix wiki](https://www.whonix.org/wiki/VPN-Firewall)
- [archlinux wiki](https://wiki.archlinux.org/index.php/PPTP_Client)
- [Fedora forum](https://forums.fedoraforum.org/showthread.php?311519-PPTP-VPN-stopped-working-after-kernel-update)

I also referred to individual blogs for extra information:
1. https://linuxconfig.org/how-to-establish-pptp-vpn-client-connection-on-centos-rhel-7-linux
2. https://www.photonvps.com/billing/index.php?rp=/knowledgebase/58/How-to-setup-VPN-server--PPTP-on-CentOS-RedHat-and-Ubuntu.html

> Need ultimate working configuration like a openvpn in Qubes 4.0 (qubes-contrib, qubes-tunnel).
> It will be good if specific package will be created (`rpm` or `deb`) (bash script with specific iptables rules and modprobe)
> User must install it on `template`, create `proxy AppVM` based on `sys-firewall` (why `sys-net`?), check `provides network`, maybe enable specific `service` and enter `username`, `password` and `gateway` to establish connection.
> 
Creating a separate package for this sounds like a good idea. At the moment, the connection process is cumbersome and can definitely be improved.
> It also good for `openconnect` based on `Cisco ASA` office vpn.
> Install `qubes-contrib` and choose correct package for you - `qubes-tunnel`, `qubes-tunnel-pptp` or `qubes-tunnel-openconnect`.

**Comment by unman** [comment]
On Wed, Jul 22, 2020 at 06:53:49AM -0700, Shriti Chandra wrote:
> @minic0m 
> > 
> > 
> > @chandrashritii did you test it?
> 
> I haven't tested it but I have referred to reliable sources, including previously documented issues on the same topic.

imo every piece of documentation should be tested ad nauseam before it
is posted.

**Comment by awokd** [comment]
> After seeing this PR, I wonder if we should move this to https://github.com/Qubes-Community

I'm available if that's the verdict.

**Comment by n5k-max** [comment]
@chandrashritii @unman @awokd 
I follow this guide and it doesn't work on Qubes 4.0
I use default scheme : pptp-template (network-manager-pptp, network-manager-pptp-gnome, pptp-linux)
Create ProxyVM provides network and attach sys-net as network (added service network-manager)

```
[user@sys-net ~]$ lsmod | grep pptp
nf_nat_pptp            16384  0
nf_nat_proto_gre       16384  1 nf_nat_pptp
nf_conntrack_pptp      16384  1 nf_nat_pptp
nf_conntrack_proto_gre    16384  1 nf_conntrack_pptp
nf_nat                 36864  5 nf_nat_ipv4,xt_nat,nf_nat_pptp,nf_nat_proto_gre,xt_REDIRECT
nf_conntrack          163840  11 xt_conntrack,nf_nat,nft_ct,xt_state,nf_conntrack_pptp,ipt_MASQUERADE,nf_nat_ipv4,xt_nat,nf_nat_pptp,nf_conntrack_proto_gre,xt_REDIRECT
```
```
[user@sys-net ~]$ sudo iptables -L
Chain FORWARD (policy DROP)
ACCEPT     gre      X.X.X,X  anywhere
```
```
ser@sys-vpn-work-pptp:~$ sudo iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     gre  -- 
```

```
user@sys-vpn-work-pptp:~$ sudo journalctl | grep pppd
Jul 31 14:57:28 sys-vpn-work-pptp systemd[1]: pppd-dns.service: Succeeded.
Jul 31 15:00:57 sys-vpn-work-pptp pppd[1099]: Plugin /usr/lib/pppd/2.4.7/nm-pptp-pppd-plugin.so loaded.
Jul 31 15:00:57 sys-vpn-work-pptp NetworkManager[573]: Plugin /usr/lib/pppd/2.4.7/nm-pptp-pppd-plugin.so loaded.
Jul 31 15:00:57 sys-vpn-work-pptp pppd[1099]: pppd 2.4.7 started by root, uid 0
Jul 31 15:00:57 sys-vpn-work-pptp pppd[1099]: Using interface ppp0
Jul 31 15:00:57 sys-vpn-work-pptp pppd[1099]: Connect: ppp0 <--> /dev/pts/1
Jul 31 15:01:18 sys-vpn-work-pptp pppd[1099]: Modem hangup
Jul 31 15:01:18 sys-vpn-work-pptp pppd[1099]: Connection terminated.
Jul 31 15:01:18 sys-vpn-work-pptp pppd[1099]: Exit.
Jul 31 15:09:24 sys-vpn-work-pptp pppd[1458]: Plugin /usr/lib/pppd/2.4.7/nm-pptp-pppd-plugin.so loaded.
Jul 31 15:09:24 sys-vpn-work-pptp NetworkManager[573]: Plugin /usr/lib/pppd/2.4.7/nm-pptp-pppd-plugin.so loaded.
Jul 31 15:09:24 sys-vpn-work-pptp pppd[1458]: pppd 2.4.7 started by root, uid 0
Jul 31 15:09:24 sys-vpn-work-pptp pppd[1458]: Using interface ppp0
Jul 31 15:09:24 sys-vpn-work-pptp pppd[1458]: Connect: ppp0 <--> /dev/pts/1
Jul 31 15:09:45 sys-vpn-work-pptp pppd[1458]: Modem hangup
Jul 31 15:09:45 sys-vpn-work-pptp pppd[1458]: Connection terminated.
Jul 31 15:09:45 sys-vpn-work-pptp pppd[1458]: Exit.
```

Any ideas? On another laptop with clean ubuntu host it works.

**Comment by n5k-max** [comment]
Another way - trying throu docker

pptp_1  | using channel 36
pptp_1  | Using interface ppp0
pptp_1  | Connect: ppp0 <--> /dev/pts/0
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | sent [LCP ConfReq id=0x5 <asyncmap 0x0> <magic 0x69f96273> <pcomp> <accomp>]
pptp_1  | Script ?? finished (pid 34), status = 0x0
pptp_1  | Script pptp X.X.X.X --nolaunchpppd finished (pid 30), status = 0x0
pptp_1  | Modem hangup
pptp_1  | Connection terminated.```
```
```
47: ppp0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 3
    link/ppp 
```
```
Aug 01 00:23:46 docker-pptp systemd-udevd[2396]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Aug 01 00:24:07 docker-pptp systemd-udevd[2458]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Aug 01 00:24:29 docker-pptp systemd-udevd[2470]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
```

**Comment by andrewdavidwong** [comment]
It's looking like Qubes-Community might be a better place for this.

**Comment by 99ninetynine** [comment]
>  haven't tested it but I have referred to reliable sources, including previously documented issues on the same topic.
> For the firewall configuration, I referred to a previously asked user issue, answered by @unman, which can be found [here.](https://www.mail-archive.com/qubes-users@googlegroups.com/msg12279.html)

Sorry, these firewall rules are not enough. they are only suitable for standalone vanilla linux, not for Qubes.

@andrewdavidwong 
I didn’t see anyone succeed there

**Comment by andrewdavidwong** [comment]
I'm closing this PR now so that this documentation can be moved to Qubes-Community, where it can also be tested and any questions or disagreements can be hashed out in collaboration.

**Pull request closed without merging**
