### PR TITLE
Add appvms-networkmanager.md

### PR DESCRIPTION
**Pull request by jdorel**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
I'm skeptical that this merits its own dedicated page. Perhaps it should instead be added to one of the System docs in the Developer section. What do you think, @marmarek?

**Comment by jdorel** [comment]
Maybe I could split this in two ?
- In UserDocumentation/AdvancedConfiguration/Networking
- In DevelopersDocumentation/System/Networking#NetworkManager_in_AppVMs

**Comment by marmarek** [comment]
Yes, it doesn't warrant separate page. I'd add this all to the existing "VM network in Qubes" page. Besides the fact that created connections are persistent, I don't think user really should care about being it symlink or anything else.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the prolonged lack of activity. If you would like to take up this PR again, please leave a comment, and we'll be happy to reopen this. Thank you.

**Pull request closed without merging**
