### PR TITLE
Added URL to patches

### PR DESCRIPTION
**Pull request by Ashaman-**
Added the URL to the folder of the github repo containing the patches for Qubes Manager

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
There's a better way to link to attachments; see here for instructions:

https://www.qubes-os.org/doc/doc-guidelines/

However, I'm not sure what the motivation is for linking to these very old files for a long-deprecated Qubes version. Historical interest?

**Comment by Ashaman-** [comment]
I realized that shortly after making the submission.. considering how prominently that page is linked in the qubes documentation, that isn't immediately obvious.
Is it even possible to implement bridging in Qubes 4? If not, that page should have a giant banner that says "deprecated" at the top...

**Comment by andrewdavidwong** [comment]
> I realized that shortly after making the submission.. considering how prominently that page is linked in the qubes documentation, that isn't immediately obvious.

What do you mean?

> Is it even possible to implement bridging in Qubes 4? If not, that page should have a giant banner that says "deprecated" at the top...

I don't know, but at least the section you're modifying says "(Qubes R2B2)," so it's obviously very old.

**Comment by andrewdavidwong** [comment]
Given the foregoing discussion, I don't see the value in merging this. However, we're always open to reconsidering if anyone has additional thoughts to share on the matter.

**Pull request closed without merging**
