### PR TITLE
how to avoid creating an ubuntu 14.4 LTS template

### PR DESCRIPTION
**Pull request by john-david-r-smith**
maybe this method should be added as a general point.
e.g.: "Simulating qubes features for vms without qubes support"

a similar thing could be done for windows hvms, too.
you could use teamviewer or vnc and get audio this way (though i don't know whether vnc can stream audio).

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
IMHO, the `Ubuntu 14.4 LTS` link is a bit misleading. Would you mind cleaning that up a bit? (You could just use "see" like you do for the later ML link.)

**Comment by john-david-r-smith** [comment]
like this?

**Comment by andrewdavidwong** [comment]
The link is better, but please don't use HTML for line breaks when you can make them with Markdown (two spaces at the end of the line).

**Comment by john-david-r-smith** [comment]
done. (i never stop learning)

**Comment by andrewdavidwong** [comment]
Thanks!

**Pull request merged**
