### PR TITLE
consistent dracut commands across docs

### PR DESCRIPTION
**Pull request by awokd**

### CODE REVIEW

**Comment by marmarek** [comment]
Any specific reason for `-H` option?

**Comment by awokd** [comment]
Per https://github.com/QubesOS/qubes-doc/pull/592#issuecomment-366460426
Haven't tested with a non-default keyboard layout so I'm not completely sure it's required, but looks like it was still an issue with Fedora 23.

**Comment by marmarek** [comment]
Ah, so this (or related thing) might also fix  https://github.com/QubesOS/qubes-issues/issues/2971?

**Comment by awokd** [comment]
Yes, that definitely looks related but I'm surprised, thought it was only the older Fedora versions that had the problem. Not sure it would be a good idea to default the installer to use `-H`; sometimes it's useful to be able to install Qubes on one PC then transfer the disk to another.

**Comment by awokd** [comment]
So, from https://github.com/marmarek/qubes-core-admin-linux/commit/bcf7c9e978681991c776b8bb1c8172af83e0d606, we want to keep `-H` in here, correct?

**Comment by marmarek** [comment]
In fact this all makes no difference. Because `/usr/lib/dracut/dracut.conf.d/01-dist.conf` contains `hostonly="yes"`.

**Comment by awokd** [comment]
OK! Can this be merged as is then, to capture the `uname -r` changes, or should I remove `-H` first?

**Comment by marmarek** [comment]
In the light of this finding, I'd remove -H from here. Otherwise it will be misleading (suggesting that -H is really needed to get hostonly mode).

**Pull request merged**
