### PR TITLE
Updated installation and usage instructions

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by ptitdoc** [comment]
The activation instruction could probably be improved if we preload my GPG key into the template (without necessarilly signing it).
This would avoid opening the firewall.

**Comment by andrewdavidwong** [comment]
@marmarek, what do you think?

**Comment by marmarek** [comment]
I don't know how key management in Archlinux works, but what about simply shipping a key in separate file and let the user import it?

**Comment by ptitdoc** [comment]
In Archlinux, there are basically using GPG trust. They generate a keyring, import five developpers master keys, these keys signed other developers keys.
Archlinux also uses a specific package (archlinux-keyring) to do all these tasks automatically and offline.
I can probably create such a package, or as you suggest put the file somewhere. I will thing about that.

**Comment by ptitdoc** [comment]
Such a package can also probably be used to change keys at some point.

**Pull request merged**
