### PR TITLE
Update optical-discs.md

### PR DESCRIPTION
**Pull request by dancingonadragon**
More verbose language on just how to use a USB optical drive.

### CODE REVIEW

**Comment by dancingonadragon** [comment]
Not clear why this failed. First time user of GIT. Anything else I should do?

**Comment by andrewdavidwong** [comment]
> using the device-manager-icon widget is buggy

Instead of putting this in the documentation, we would rather fix the bugs in the widget and have that be the user-friendly solution for using a USB optical drive. If the bugs you're experiencing haven't already been reported, please [report them](https://www.qubes-os.org/doc/reporting-bugs/).

> Not clear why this failed. First time user of GIT. Anything else I should do?

We use a simple typo/misspelling check that fails whenever it encounters an unknown spelling, in this case `sr0` and `wodim`. Since these spellings aren't erroneous, there's nothing to worry about.

**Comment by dancingonadragon** [comment]
My experience with getting an optical USB drive working was needlessly confusing about the preferred way to attach and mount and, in some cases, write to these devices. I spent many hours trying to understand which of the many ways offered was the preferred and/or correct method for my situation. I needed a simple procedure to follow and I found this seriously lacking. The section about optical disks is the best place to do this. I believe fixing the widget is a great idea but those who need to use the terminal or those who want to know better how to control attachment themselves or those who don't have a fixed widget would all benefit from having clear and concise instructions. IMHO.
Not sure if I actually encountered any bugs at this point. Thank you.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by andrewdavidwong** [comment]
> My experience with getting an optical USB drive working was needlessly confusing about the preferred way to attach and mount and, in some cases, write to these devices. I spent many hours trying to understand which of the many ways offered was the preferred and/or correct method for my situation. I needed a simple procedure to follow and I found this seriously lacking. The section about optical disks is the best place to do this. I believe fixing the widget is a great idea but those who need to use the terminal or those who want to know better how to control attachment themselves or those who don't have a fixed widget would all benefit from having clear and concise instructions. IMHO. Not sure if I actually encountered any bugs at this point. Thank you.

I agree that it is good and important to have the type of documentation you are adding. My comment was just about the sentence "using the device-manager-icon widget is buggy," which I removed for the reasons explained above. This was a minor parenthetical remark in your text, and its removal doesn't detract from the main point of your documentation. Nonetheless, I wanted to provide you with an explanation for the change.

**Comment by dancingonadragon** [comment]
Ok. I misunderstood the thrust of your comment. Makes sense. Thank you for the commit.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
