### PR TITLE
Cover new reinstall feature in qubes-dom0-update

### PR DESCRIPTION
**Pull request by tasket**
New support for reinstalling templates in-place was added in Qubes 3.1.

### CODE REVIEW

**Comment by tasket** [comment]
Issue https://github.com/QubesOS/qubes-issues/issues/2061

**Comment by tasket** [comment]
One issue about the current wording:

The Manual section states that a manual reinstall should be done "...if you wish to do a clean reinstallation of a template in order to upgrade to a different version".

My understanding of the new/automatic process is that it provides a clean reinstallation, to the point of removing the old private.img, so it should also be able to do the job for reverting, upgrading, etc.

**Comment by tasket** [comment]
One issue about the current wording:

The Manual section states that a manual reinstall should be done "...if you wish to do a clean reinstallation of a template in order to upgrade to a different version".

My understanding of the new/automatic process is that it provides a clean reinstallation, to the point of removing the old private.img, so it should also be able to do the job for reverting, upgrading, etc.

**Comment by andrewdavidwong** [comment]
@tasket: Updated the wording [here](https://github.com/QubesOS/qubes-doc/commit/65fc5bc0c58887333dd08137e5915fb9354e7237). Thanks!

**Pull request merged**
