### PR TITLE
Fix saltstack document links

### PR DESCRIPTION
**Pull request by zpc0**
- Fix link to command states
- Use docs.saltproject.io

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@unman: Trying to give Marek a break with PR reviews by assigning them to other team members, when appropriate. I'm guessing the reason for this one is because saltstack.com is commercial, but I know nothing about the proposed replacement domain. Seems uncanny that almost every URL would work as a direct drop-in domain replacement. I'm sure there's a story there. I think I've seen you mention something about this recently, so I figured you might be a good person to review this.

**Comment by unman** [comment]
On Mon, Jun 14, 2021 at 05:50:30AM -0700, Andrew David Wong wrote:
> @unman: Trying to give Marek a break with PR reviews by assigning them to other team members, when appropriate. I'm guessing the reason for this one is because saltstack.com is commercial, but I know nothing about the proposed replacement domain. Seems uncanny that almost every URL would work as a direct drop-in domain replacement. I'm sure there's a story there. I think I've seen you mention something about this recently, so I figured you might be a good person to review this.
> 

No problem - the old link redirects, so it doesn't impact users at all.
I have a little more time now, so allocate away.

**Comment by andrewdavidwong** [comment]
> No problem - the old link redirects, so it doesn't impact users at all. I have a little more time now, so allocate away.

Thanks, @unman! Please leave a review (either accept or reject) when you have a chance.

**Comment by zpc0** [comment]
I split commit into two for easier review.

Commit about saltproject.io is optional.
If saltstack.com is preferred, I will drop the related commit from pr.

**Review by unman — APPROVED** [review]
@andrewdavidwong These changes are good.
My updated key not good for doc signing, so please merge.

**Comment by andrewdavidwong** [comment]
@fepitre @marmarek: I think something has gone with the GitLab CI check here. It seems to be based on a very old version of the website or something.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
I think these CI failures are still spurious, @fepitre.

**Comment by andrewdavidwong** [comment]
Also, I don't know why GitHub says there's a merge conflict. When I checkout and pulll, Git doesn't indicate that there's a merge conflict. Perhaps this and the CI problem are related somehow?

**Comment by zpc0** [comment]
Rebase only.
The mysterious conflict warning is now fixed.

**Comment by andrewdavidwong** [comment]
PipelineRetry

**Pull request merged**
