### PR TITLE
Tweak NetworkManager-based MAC randomization

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
Hmm, now I wonder if the second commit is misleading, because `ethernet.cloned-mac-address=stable` applies to NetworkManager connection *profiles*, which could each be used to connect to many different Ethernet networks. Would `ethernet.cloned-mac-address=random` be a better example to include?

**Comment by rustybird** [comment]
Force pushed reworded commit that referes to "connection profiles" instead of "connections"

**Comment by andrewdavidwong** [comment]
> Hmm, now I wonder if the second commit is misleading, because `ethernet.cloned-mac-address=stable` applies to NetworkManager connection profiles, which could each be used to connect to many different Ethernet networks. Would `ethernet.cloned-mac-address=random` be a better example to include?

I think this is ok, if for no other reason than that it's consistent with `wifi.cloned-mac-address=stable`, but if @tasket or @marmarek have any objections, we can change it.

**Comment by tasket** [comment]
The doc states that it affects the Wifi address, but the edit expands that to ethernet. May want to change the wording in the paragraph directly above to reflect that.

Also, although the doc refers the reader to the man page, it could also use a quick explanation that 'stable=random that persists per boot session' and 'random=random each time a link goes up'.

**Comment by andrewdavidwong** [comment]
Thanks, @tasket. [Updated.](https://github.com/QubesOS/qubes-doc/commit/4eb23c0e09511dd4c3ca6805874ba499bd052db8)

**Pull request merged**
