### PR TITLE
awesomewm: updated instructions for awesome 4.3 in Qubes 4.1

### PR DESCRIPTION
**Pull request by 3hhh**
This is a draft as I haven't yet tested it.

I'll test it once 4.1 is out.

### CODE REVIEW

**Comment by 3hhh** [comment]
I successfully tested the force-pushed version on 4.1rc1.

Feel free to merge for 4.1.

**Comment by andrewdavidwong** [comment]
> I successfully tested the force-pushed version on 4.1rc1.
> 
> Feel free to merge for 4.1.

Thanks. We don't have separate 4.1 docs yet, so this will be on hold until then or until 4.1 is a stable release (whichever comes first) so as not to overwrite 4.0 information upon which current 4.0 stable users may presently be relying.

**Comment by andrewdavidwong** [comment]
We need someone to review this (especially the code), but I'm not sure who from the community or team is well-versed in this. @marmarek, any suggestions (assuming you don't have time to review it yourself)?

**Comment by andrewdavidwong** [comment]
@3hhh: Could you please make sure to follow [this](https://www.qubes-os.org/doc/documentation-style-guide/#release-specific-documentation) so that the page is still useful for those who remain on Qubes 4.0 (which will still be supported for six months)?

**Comment by 3hhh** [comment]
On 2/7/22 10:36, Andrew David Wong wrote:
> @3hhh: Could you please make sure to follow [this](https://www.qubes-os.org/doc/documentation-style-guide/#release-specific-documentation) so that the page is still useful for those who remain on Qubes 4.0 (which will still be supported for six months)?

What about just linking to github for the [4.0 version](https://github.com/QubesOS/qubes-doc/blob/3806ecf33878d9605054de2276d691230188a125/user/advanced-topics/awesomewm.md) at the top of the page?

There won't be any edits during the next 6 months for 4.0 anymore anyway (IIRC I was the only one to ever touch that page with actual content) and even if so, such edits could be done in a 4.0 branch.

**Comment by andrewdavidwong** [comment]
> 
> On 2/7/22 10:36, Andrew David Wong wrote:
> > @3hhh: Could you please make sure to follow [this](https://www.qubes-os.org/doc/documentation-style-guide/#release-specific-documentation) so that the page is still useful for those who remain on Qubes 4.0 (which will still be supported for six months)?
> 
> What about just linking to github for the [4.0 version](https://github.com/QubesOS/qubes-doc/blob/3806ecf33878d9605054de2276d691230188a125/user/advanced-topics/awesomewm.md) at the top of the page?

Hmm, interesting idea. I suppose that might be good enough (and be the lesser of two evils).

> There won't be any edits during the next 6 months for 4.0 anymore anyway (IIRC I was the only one to ever touch that page with actual content) and even if so, such edits could be done in a 4.0 branch.
> 

Unfortunately, we don't have separate branches for the documentation (yet), which is why the release-specific-docs policy is what it is (for now). See the linked issue in my link above for explanation of why.

**Comment by andrewdavidwong** [comment]
> We need someone to review this (especially the code), but I'm not sure who from the community or team is well-versed in this. @marmarek, any suggestions (assuming you don't have time to review it yourself)?

@DemiMarie, any idea who might be able to review this?

**Comment by andrewdavidwong** [comment]
Now that 4.1 is stable and 4.0 has almost reached EOL, this can be merged as soon as it has been reviewed and approved, but I have still been unable to find a reviewer for it. @marmarek, @DemiMarie, any suggestions for who I can ask to review this?

**Comment by DemiMarie** [comment]
> Now that 4.1 is stable and 4.0 has almost reached EOL, this can be merged as soon as it has been reviewed and approved, but I have still been unable to find a reviewer for it. @marmarek, @DemiMarie, any suggestions for who I can ask to review this?

I will do it myself.

**Comment by 3hhh** [comment]
Should this page maybe go to the community doc? Then I could close down this PR.

Your upstream version of the page is useless with 4.1 anyway.

**Comment by andrewdavidwong** [comment]
> Should this page maybe go to the community doc? Then I could close down this PR.

@marmarek, would you be OK with this?

> Your upstream version of the page is useless with 4.1 anyway.

Not sure what you mean. By "upstream," do you mean "current"?

**Pull request closed without merging**
