### PR TITLE
Setup example of an encrypted second HDD on R4.0

### PR DESCRIPTION
**Pull request by Galland**
This is too complex and error prone not to facilitate users' lives with an example of the few commands needed to perform this.

### CODE REVIEW

**Comment by tasket** [comment]
You may want to consider adding a GUI example as well. The `gnome-disks` tool very nicely handles both LUKS and volume groups.

**Comment by andrewdavidwong** [comment]
Please don't use `#` for comments when giving command-line instructions. It's ambiguous with a root prompt. You can instead make those comments text outside and preceding each code block instruction line.

**Comment by Galland** [comment]
@tasket there is no gnome-disks in dom0

**Comment by tasket** [comment]
@Galland gnome-disks isn't pre-installed in dom0, but it is available from the repository.

**Pull request merged**
