### PR TITLE
Create new section for external docs

### PR DESCRIPTION
**Pull request by andrewdavidwong**
For: QubesOS/qubes-issues#4693

Complementary PR: https://github.com/QubesOS/qubesos.github.io/pull/125

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
These Travis CI failures should be fixed when https://github.com/QubesOS/qubesos.github.io/pull/125 is merged.

**Comment by marmarek** [comment]
I think some of docs you've moved to "external" should stay in main documentation, as they are primary docs about specific software we maintain to some degree. This applies to:
 - window managers: KDE, i3, awesome
 - yubikey guide (it's about qubes-yubikey-dom0 package)
 - vm-sudo (with the goal of https://github.com/QubesOS/qubes-issues/issues/2695)
 - device-handling-security.md

**Comment by andrewdavidwong** [comment]
> I think some of docs you've moved to "external" should stay in main documentation, as they are primary docs about specific software we maintain to some degree. This applies to:
> 
> * window managers: KDE, i3, awesome
> * yubikey guide (it's about qubes-yubikey-dom0 package)
> * vm-sudo (with the goal of [QubesOS/qubes-issues#2695](https://github.com/QubesOS/qubes-issues/issues/2695))
> * device-handling-security.md

Ok, thanks! I've moved all of these back (https://github.com/QubesOS/qubes-doc/commit/f58b6db36d825e92af7c2ed6223d06aef3b66e82).

**Comment by andrewdavidwong** [comment]
Oops, missed moving some of the underlying files (https://github.com/QubesOS/qubes-doc/commit/075c6df1698c52312f02249499ba21bb28536b4d).

**Comment by marmarek** [comment]
Spotted another docs that should be in core docs:
 - gui-configuration.md
 - tentatively resize-disk-image.md
 - uefi-troubleshooting
 - newer-hardware-troubleshooting.md

**Comment by andrewdavidwong** [comment]
> Spotted another docs that should be in core docs:
> 
> * gui-configuration.md
> * tentatively resize-disk-image.md
> * uefi-troubleshooting
> * newer-hardware-troubleshooting.md

Thanks. Moved back: https://github.com/QubesOS/qubes-doc/commit/994632280a54a219cf30b59728b6431b0de3fcae

**Pull request merged**
