### PR TITLE
faq: add steps to edit update repositories

### PR DESCRIPTION
**Pull request by awokd**
per https://github.com/QubesOS/qubes-issues/issues/3737#issuecomment-383401560

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Well, this won't work around the problem in normal cases (e.g., when the server has a temporary problem).

**Comment by andrewdavidwong** [comment]
I'm going to wait on a response to https://github.com/QubesOS/qubes-issues/issues/3737#issuecomment-383418890 before merging this, and even then, it will probably be better to add the revised version (the same as what appears in the announcement) to avoid confusion.

**Comment by awokd** [comment]
Makes sense. Should I close?

**Comment by awokd** [comment]
ok

**Pull request closed without merging**
