### PR TITLE
Reworked the page structure, added USBVM use case

### PR DESCRIPTION
**Pull request by sprig-florist**
Expanded the description of a standard NetVM with qubes-input-proxy-sender, so that a 3.2 standard installation with NetVM=UsbVM does not leave USB broken when replacing the NetVM template with the fedora-minimal one.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
This is good for people who have "NetVM=USBVM", but it's unnecessary for people who have separate VMs for those two. Instead of encouraging everyone to install the extra package (including people for whom it's unnecessary), why not instead encourage people to install it only if they need it?

**Comment by sprig-florist** [comment]
Better? Also, would it make sense to create a more nicely structured table?
Something like this:

Purpose | Description | Packages
--- | --- | ---
**Firewall** | No extra packages are needed for the template to work as a firewall | 
**NetVM** | These packages are needed for the template to work as a NetVM | NetworkManager NetworkManager-wifi network-manager-applet  wireless-tools dbus-x11 dejavu-sans-fonts tinyproxy
**USBVM** | If you want this template to allow USB input forwarding, you will need to install one extra package. | qubes-input-proxy-sender

**Comment by andrewdavidwong** [comment]
Yes, much better! And that table would be even better!

**Comment by sprig-florist** [comment]
@andrewdavidwong here it is. 

The structure is almost completely new, I have reworked most of the content, see commit comments.
Feedback appreciated, if changes are needed!

**Comment by andrewdavidwong** [comment]
Looks fantastic; thanks for putting in the work on this! I just added a minor cleanup commit on top of yours and merged.

**Pull request merged**
