### PR TITLE
make commands more copy and paste friendly

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Part of the reason for having the terminal prompts is to remind the reader which VM the commands should be entered in. Are they really *that* copy/paste unfriendly? I mean, can't one simply not copy the terminal prompt part?

**Comment by adrelanos** [comment]
Yes, because otherwise you could just double click into the field and it would select all. No matter how long the line is. If you manually click to select, it's easier to forget something. Saw this quite a few time when supporting users.

**Comment by andrewdavidwong** [comment]
Ok, sounds good.

**Comment by andrewdavidwong** [comment]
Actually, I think that if you're going to remove these, you need to precede each command (not in the code block, but on the line above it) with something like "in dom0" or "in `debian-8`". Otherwise it's too confusing where each command should be entered.

**Comment by andrewdavidwong** [comment]
FWIW, it's extremely common in instructions to include `$` at the beginning of a code block for a terminal command ([example](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#set-up-the-repository)). This also interferes with the "copy/paste the whole code block" method, so I'm not sure we really need to go out of our way to support that method (i.e., since almost no one else does).

**Comment by adrelanos** [comment]
> Actually, I think that if you're going to remove these, you need to precede each command (not in the code block, but on the line above it) with something like "in dom0" or "in debian-8". Otherwise it's too confusing where each command should be entered.

Agreed.

> FWIW, it's extremely common in instructions to include $ at the beginning of a code block for a terminal command (example). This also interferes with the "copy/paste the whole code block" method, so I'm not sure we really need to go out of our way to support that method (i.e., since almost no one else does).

That's a hard decision. I would defer it to a usability designer. The ux designer who worked with us (bnvk) wrote/rewrote https://www.qubes-os.org/doc/whonix/install/ (among other Whonix documentation pages on qubes-os.org) where he preferred the "in dom0" plus copy/paste friendly instructions. That's why I would think that's the way to go.

**Comment by andrewdavidwong** [comment]
I don't have a strong opinion either way, so long as it's unambiguous which VM each command should be entered in.

**Comment by andrewdavidwong** [comment]
This PR is being closed because there has been no activity on it in over a year. However, if anyone would like it to be reopened, simply leave a comment saying so, and we'll be happy to reopen it. Thank you.

**Pull request closed without merging**
