### PR TITLE
Release-specific docs

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Specify releases in permalinks.

QubesOS/qubes-issues#5308

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by andrewdavidwong** [comment]
@fepitre, @marmarek: Does `TestDeploy` not work in qubes-doc? I'm trying to deploy both this and https://github.com/QubesOS/qubesos.github.io/pull/185 at the same time so that I can see the result of both together.

**Comment by marmarek** [comment]
> I'm trying to deploy both this and [QubesOS/qubesos.github.io#185](https://github.com/QubesOS/qubesos.github.io/pull/185) at the same time

Sadly this mechanism doesn't support deploying two PRs at the same time. One will override the other...

**Comment by marmarek** [comment]
TestDeploy

**Comment by marmarek** [comment]
What you can try, is to bump qubes-doc submodule in the other PR (in a separate commit), and deploy then. I'm not 100% sure it will work, but there is a chance.

**Comment by andrewdavidwong** [comment]
Superseded by migration to RTD.

**Pull request closed without merging**
