### PR TITLE
Update Amazon book link to current edition

### PR DESCRIPTION
**Pull request by jpouellet**
Also change links to https while at it

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@jpouellet:

```
$ gpg2 --recv 0xE7E455013D042EA1
gpg: keyserver receive failed: No data
```

**Comment by andrewdavidwong** [comment]
(This PR doesn't require signed commits; just letting you know.)

**Comment by jpouellet** [comment]
@andrewdavidwong Correct. It's a temporary key that I intentionally didn't upload to the keyservers.

Pubkey was submitted with my first PR here: https://github.com/QubesOS/qubes-installer-qubes-os/pull/8#commitcomment-19406400

**Comment by andrewdavidwong** [comment]
@jpouellet: Ok, no problem. Feel free to let me know when you have a permanent key.

**Pull request merged**
