### PR TITLE
Add SecBrowser to external documentation.

### PR DESCRIPTION
**Pull request by 0brand**
SecBrowser is a new security-focused (clearnet) browser developed by the Whonix devs. SecBrowser is the result of the research based on the use of Tor Browser for security not anonymity aka [Tor Browser without Tor](https://forums.whonix.org/t/todo-research-and-document-how-to-use-tor-browser-for-security-not-anonymity-how-to-use-tbb-using-clearnet/3822). 

The SecBrowser documentation (both markdown tables etc) looked perfect when rendered locally. I saw several Qubes/doc pages with a few links formatted like a reference " [1] "so I included a few encapsulated in **< sup>** [text | link)  **< /sup>** which creates fake foot notes. I thought readers would find it useful to be able to click on the link to see where the info came from. I can easily remove those if you'd like.

Please let me know if any changes are needed.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Appreciate the contribution, but I think the current plan is to move external docs _out_ of `qubes-doc` to https://github.com/Qubes-Community (see https://github.com/QubesOS/qubes-issues/issues/4693).

@taradiddles, @awokd: Can you accommodate @0brand's documentation in the Community docs?

**Comment by 0brand** [comment]
>but I think the current plan is to move external docs out of qubes-doc to https://github.com/Qubes-Community (see QubesOS/qubes-issues#4693).

My apologies, I wasn't aware of the migration to Qubes-Community. 

@awokd I'm not sure what sub directory to submit the pull request.  Qubes-Community/Contents/docs/?

**Comment by andrewdavidwong** [comment]
> My apologies, I wasn't aware of the migration to Qubes-Community.

No apology necessary! Look forward to seeing your documentation over there. :slightly_smiling_face:

**Comment by awokd** [comment]
> @awokd I'm not sure what sub directory to submit the pull request.  Qubes-Community/Contents/docs/?

Yes, `customization` in there should work. Thanks!

**Pull request closed without merging**
