### PR TITLE
List Non-free Components

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fix https://github.com/QubesOS/qubes-issues/issues/5163.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
`License.md` might be problematic for the reasons discussed in https://github.com/QubesOS/qubes-issues/issues/4219.

**Comment by tapaswenipathak** [comment]
np, yea, if you can enlighten me  -

- https://www.qubes-os.org/partners/

Should I add any free components as well? Qubes architecture components are mostly free.

**Comment by andrewdavidwong** [comment]
> np, yea. If you can enlighten me -
> 
> * https://www.qubes-os.org/partners/
> 
> Should I add any free components as well other than these?

Sorry, I don't understand what you're asking here. The Partners page doesn't really have anything to do with free or non-free software components included in Qubes OS. Rather, the Partners page acknowledges organizations and individuals who support the Qubes OS Project (e.g., through sizable donations).

**Comment by tapaswenipathak** [comment]
@andrewdavidwong I looked at https://www.qubes-os.org/attachment/wiki/posts/qubes-components.png, I don't think anything in these is non free. What do you suggest me adding for the ticket?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I looked at https://www.qubes-os.org/attachment/wiki/posts/qubes-components.png, I don't think anything in these is non free. What do you suggest me adding for the ticket?

If Qubes OS contains no non-free components, then I suppose there should just be a statement like, "Qubes OS does not contain any non-free components" instead of a list.

**Comment by andrewdavidwong** [comment]
Requesting "review" from @marmarek just to confirm that we (the Qubes OS Project) believe that Qubes OS contains no non-free components.

It just occurred to me that this could be controversial unless we clearly define the term "non-free."

**Comment by marmarek** [comment]
I don't think saying "Qubes OS does not contain any non-free components" will be true. We include Debian and Fedora images, and those may contain non-free components. For example we ship firmware packages installed by default. See [here](https://www.gnu.org/distros/common-distros.en.html) for details.
There are no qubes-specific components that are non-free.

**Comment by tapaswenipathak** [comment]
Can you tell me more on what should I write? Should I write all non free components or should I just write a48ae2f?

**Comment by andrewdavidwong** [comment]
> There are no qubes-specific components that are non-free.

This part is important to add.

In general, this deserves more explanation than a one-liner.

**Comment by tapaswenipathak** [comment]
@andrewdavidwong I didn't get you, I have removed that line. a48ae2f is ok? I can expand that item more, lemme know.

**Comment by andrewdavidwong** [comment]
@tapaswenipathak: I sincerely appreciate the effort you're making to contribute PRs, but the time required to review each one is turning out to be far longer than usual and longer than it would take the write the content ourselves. In light of this, I'm afraid I have to decline this PR.

**Comment by tapaswenipathak** [comment]
No problem, expanding the item is taking my time as well.

**Pull request closed without merging**
