### PR TITLE
disk-trim add systemd fstrim and efi initrd rebuild step

### PR DESCRIPTION
**Pull request by awokd**
from https://mail-archive.com/qubes-users@googlegroups.com/msg19082.html and followups

### CODE REVIEW

**Comment by awokd** [comment]
Intentionally skipping the `dracut -H` option in the EFI section per the man page comment about it:
>This has the
drawback, that you can’t put the disk on another controller or machine,
and that you can’t switch to another root filesystem, without recreating
the initramfs image. The usage of the --hostonly option is only for
experts and you will have to keep the broken pieces. 

Left it in the GRUB config section because it was in **bold** so it seemed pretty important to someone at some time, but I don't know if it's still the best recommendation?

**Comment by andrewdavidwong** [comment]
@marmarek: I know that you're very busy, and a lot of qubes-doc PRs are assigned to you. Please feel free to delegate them to other Qubes team members, if you like. (I assign them to you when I'm not certain who else has the required technical expertise to review the content.)

**Comment by awokd** [comment]
And if there's something else I can/should be doing, please let me know. Travis claims a bunch of these are "failed". The ones that aren't spelling related (like this one) should be good with a re-run of Travis but it looks like the only way I can do that is to close and re-open the PRs which I imagine will generate spam.

**Comment by awokd** [comment]
Added -H because it appears to be required for non-default keyboard layouts and LUKS: https://ask.fedoraproject.org/en/question/80389/cannot-open-luks-container-with-rescue-initramfs/

**Pull request merged**
