### PR TITLE
specifiy where to change what

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by marmarek** [comment]
Oh, I see the documentation does not mention we have packaged those scripts. It's here: https://github.com/QubesOS/qubes-app-yubikey (packages available in 3.2 and 4.0 repos)

**Comment by adrelanos** [comment]
Actually, please hold.

>  +3. Create `/usr/local/bin/yubikey-auth` script your USB VM: 

This is wrong. Correcting myself. In https://groups.google.com/forum/#!topic/qubes-users/r7evJ_LoO8I you said in dom0. And since that script runs `qvm-run -u root --nogui -p sys-usb`, I am very sure I was wrong. Will correct in another PR.

**Comment by adrelanos** [comment]
From https://www.qubes-os.org/doc/yubi-key/ I also doubt the following line would work.

    hash=`head -c -1 | openssl dgst -sha1 -r | cut -f1 -d ' '`

`openssl dgst -sha1 -r` is blocking and nothing was `echo`ed.

----

Note to self:

    sudo qubes-dom0-update qubes-yubikey-dom0

**Comment by marmarek** [comment]
> openssl dgst -sha1 -r is blocking and nothing was echoed.

Actually something was echoed. pam_exec send a password on stdin.

**Pull request closed without merging**
