### PR TITLE
Update version-scheme.md

### PR DESCRIPTION
**Pull request by gutsle**
added where to find version information

### CODE REVIEW

**Comment by axon-qubes** [comment]
Would you mind adding that you can see the release in Qubes Manager --> About --> Qubes OS?

**Comment by axon-qubes** [comment]
And maybe give a command like `$ cat /etc/qubes-release`, since people who are new to Linux might not know what you mean by "you can find out in."

**Comment by gutsle** [comment]
okay, did that

**Comment by axon-qubes** [comment]
Thanks!

**Pull request merged**
