### PR TITLE
Reduce Windows confusion in 'Copying the ISO...' section

### PR DESCRIPTION
**Pull request by dksmiffs**
As discussed w/ adw and deeplow [here](https://qubes-os.discourse.group/t/qubes-installation-guide-mediatest-rufus-confusion/4763) on 2021-06-27.  I welcome any suggestions for improvement to this edit.

### CODE REVIEW

**Comment by dksmiffs** [comment]
I removed the links to the Rufus screenshots, but I couldn't find the storage of these screenshots themselves for suggested removal.

**Comment by andrewdavidwong** [comment]
Oh, my impression from the forum thread was that the instructions for Windows users would be _improved_ rather than removed entirely. I don't think we're prepared to give up on the large (probably _largest_) segment of prospective users who are able and willing to use only Windows to prepare their Qubes installation media.

**Comment by dksmiffs** [comment]
Understood. I plan to work on better ideas for a second iteration. Feel free to close this PR as you see fit.

**Comment by andrewdavidwong** [comment]
> Understood. I plan to work on better ideas for a second iteration. Feel free to close this PR as you see fit.

Thank you!

**Pull request closed without merging**
