### PR TITLE
Update Supported Versions: TemplateVMs

### PR DESCRIPTION
**Pull request by andrewdavidwong**
- Explain passing along upstream EOL notices
 - Add note regarding Debian 9 support in R4.0
 - Add section on Debian support policy

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
RetryPipeline

**Comment by andrewdavidwong** [comment]
```
htmlproofer 3.16.0 | Error:  HTML-Proofer found 2 failures!
- ./_site/doc/certified-hardware/index.html
  *  internally linking to /news/2020/03/04/nitropad-x230-qubes-certification/, which does not exist (line 315)
     <a href="/news/2020/03/04/nitropad-x230-qubes-certification/">announcement</a>
  *  internally linking to /news/2021/06/01/nitropad-t430-qubes-certification/, which does not exist (line 322)
     <a href="/news/2021/06/01/nitropad-t430-qubes-certification/">announcement</a>
```

These are false positives. Those links are good on the live website. I'm guessing this is happening because this branch is too old compared to qubes-posts or something, but I'm not sure what, if anything, should be done about that.

**Comment by marmarek** [comment]
That is weird, as this PR is in qubes-doc repo, which is independent from posts. And indeed in the CI log I see qubes-post repo checkout at fac3c45d4345ce8b63fd923b1e76ffa56bd12222. 
But there is something wrong, the recent news are indeed not generated (at least in the CI). You can download generated site from the gitlab interface (click "browse" on the right, then download site.tar.gz - clicking "download" directly will wrap it in another archive). I don't see any news from 2020 or 2021 there. I see exactly the same issue in other CI jobs since few days. This is the most recent successful one I've found: https://gitlab.com/QubesOS/qubes-doc/-/jobs/1303853734. It uses the following commits:
```
Submodule path '_doc': checked out 'e1f929b0cae6aafbc50ef9013011fb65f72d0adc'
Submodule path '_hcl': checked out '67d591dc2f1ab2a9e2fe0f706d36bdd2411bccbd'
Submodule path '_posts': checked out '14fc312b5a14bae034f7179bf1ac2c98d042d30b'
Submodule path 'attachment': checked out '0ee5e90916e1d972230af2e192f19ef7d12e005c'
```
Maybe something indeed is broken that prevents jekyll (at least the version we have in CI) to render parts of the website? I'd expect an error message in such case...

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 0ff457791cbce912c52e7e9fe9eba95592ddb831
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmDEFT0ACgkQ8yiUvpaE
k4ofiQ//QIYHLbL27hNRJFolD38fTZkgPGPOMKe7g6s/wD2+F339zzq9PYFio319
3+sGWSKDi4HE2/unRzVSEUvE44ZWwpX6zwcOuDZL/gItA8pG8TfMTG9NPuUyy5D8
xKqbJb/A+o+8bJJWgBLiRrjsHmlzIZAabTM2ki7GTjTfFE6GA5Jf41pGMoyJC6H6
qyrdMps6QuxtyMSkk/cJfZ6cUs9V3cegMz4kGqRuSzpVHPrBSfO6b2mHfrcnfU7T
/uGsdoo+fiL6jDcuvV60EUI+OzpBwuztoE3QsVsnS9azGNBNcpw18zC6kycFrTGO
FF/IC9jiLBwI3eyN91uqrxrx+EI8lsiWSz/WQNHhMXlxEmNU+H/MZ8HxxfRbiEoZ
r+ce4FMi9gUshbl22w0ABqD7/Vlc7+UigxT0Ek7Un1ge0KN22lwbfAt0kb+80Vgi
/cO6hLdMgxqT3nZnrDVYxu/96rIXB5vCX/keApW9BgRM8W0zJh+DnOwy2qFjLNYj
K0uL0PkyPM4OuV03L+EfVfBfOZpC2BoW07RbuaVZcjdvDBsOHUgRkUWjqNJnYKJF
92pnUD0bNWWZfsjct6nMdbriqibE5PCSZJ3vRAC5/LvknUdQ6aCIhkolW52pRk7q
cnAg/XMxlO4Rp+OYZVZ28+ckxB0KMN2jXV5tntTpBJNv4LwQbJc=
=T3/9
-----END PGP SIGNATURE-----
```

**Comment by andrewdavidwong** [comment]
> That is weird, as this PR is in qubes-doc repo, which is independent from posts. And indeed in the CI log I see qubes-post repo checkout at fac3c45d4345ce8b63fd923b1e76ffa56bd12222.
> But there is something wrong, the recent news are indeed not generated (at least in the CI). You can download generated site from the gitlab interface (click "browse" on the right, then download site.tar.gz - clicking "download" directly will wrap it in another archive). I don't see any news from 2020 or 2021 there. I see exactly the same issue in other CI jobs since few days. This is the most recent successful one I've found: https://gitlab.com/QubesOS/qubes-doc/-/jobs/1303853734. It uses the following commits:
> 
> ```
> Submodule path '_doc': checked out 'e1f929b0cae6aafbc50ef9013011fb65f72d0adc'
> Submodule path '_hcl': checked out '67d591dc2f1ab2a9e2fe0f706d36bdd2411bccbd'
> Submodule path '_posts': checked out '14fc312b5a14bae034f7179bf1ac2c98d042d30b'
> Submodule path 'attachment': checked out '0ee5e90916e1d972230af2e192f19ef7d12e005c'
> ```
> 
> Maybe something indeed is broken that prevents jekyll (at least the version we have in CI) to render parts of the website? I'd expect an error message in such case...

Strange. It works fine when I serve the site locally, and the live version also looks fine. @fepitre, any ideas?

**Pull request merged**
