### PR TITLE
faq: Add how to connect to WiFi

### PR DESCRIPTION
**Pull request by cgwalters**
Now, once one understands the system this does seem obvious, but
I'm not the only person who found this confusing, see e.g.:
https://groups.google.com/forum/#!topic/qubes-users/k8RceuBRwYU

### CODE REVIEW

**Comment by jpouellet** [comment]
Err... what about nm-applet?

Putting this in the FAQ seems to suggest that recommended way to configure wireless is via the command line, and seems rather unfriendly towards non-technical users.

Is this because nm-applet did not show up for you? If so, that sounds like a bug which should be investigated.

**Comment by cgwalters** [comment]
I didn't see it indeed.  I tried using the NM connection editor in the UI, but everything was greyed out.

**Comment by andrewdavidwong** [comment]
@jpouellet is correct. Merging this PR was my mistake. I didn't realize that @cgwalters was actually attempting to document a workaround for a bug. I've now reverted the merge.

@cgwalters: I suspect that this bug is uncommon, since no one else has reported it. (https://github.com/QubesOS/qubes-issues/issues/2323 and the issues it references are somewhat related to your issue but not exactly the same.) If you would like to file an issue for this, you're welcome to do so.

**Comment by cgwalters** [comment]
Ah, that makes sense - and indeed, now that I've rebooted and/or set up a network, I do see nm-applet. Agreed, this looks like https://github.com/QubesOS/qubes-issues/issues/2323 - feel free to revert.

**Pull request merged**
