### PR TITLE
Create Fedora 29 to 30 upgrade instructions

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Requested by QubesOS/qubes-issues#4845

CC: @fepitre

### CODE REVIEW

**Comment by marmarek** [comment]
@fepitre have you managed to test this instruction?

**Comment by fepitre** [comment]
Not yet. Tonight it should be done.

**Comment by fepitre** [comment]
I tested the instructions for upgrading fedora-29 and fedora-29-minimal. It succeeded without any problem. More specific tests should be done?

**Comment by marmarek** [comment]
This is ready to be merged. But in the meantime a conflict appeared.

**Comment by andrewdavidwong** [comment]
> This is ready to be merged. But in the meantime a conflict appeared.

No problem. Merged!

**Pull request merged**
