### PR TITLE
Update hardware-related docs

### PR DESCRIPTION
**Pull request by andrewdavidwong**
- Add links to "just works" list
- Improve organization
- Standardize orthography
- Wrap text
- Remove very old ML link
- Minor wording improvements

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
FYI @SvenSemmler, @deeplow

**Comment by andrewdavidwong** [comment]
Cross-link for future reference:
https://forum.qubes-os.org/t/laptops-that-just-work-with-qubes-os-r4-0-4/5560/4?u=adw

**Comment by andrewdavidwong** [comment]
Oh, crap. I just realized that `r4-0-4` is hard-coded into the URL. :frowning_face: 

However, I see that the URL will redirect to the correct thread as long as the number ("5560") is there, so I suppose I'll just edit these URLs.

**Comment by SvenSemmler** [comment]
@andrewdavidwong, @deeplow: please use https://forum.qubes-os.org/t/5560

-- 
  public key: https://www.svensemmler.org/2A632C537D744BC7.asc
fingerprint: DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong, @deeplow: please use https://forum.qubes-os.org/t/5560
> 

I considered that too, but the current URL at least gives some preview of the title. There is no difference in functionality. Do we expect to change even the part that remains? I suppose it's redundant with the anchor text, but then that would go out of date too.

**Comment by andrewdavidwong** [comment]
@SvenSemmler: Ok, I've pushed an update (https://github.com/QubesOS/qubes-doc/commit/d75a0dcfe27a02b554adef70f60ac99439de8747) that uses the shorter URL (least chance of things going wrong in the future that way, I suppose). I also decided to make the anchor text more generic, since we might decide to change the thread title in the future. For example, we might start including non-laptop hardware. For another example, someone might complain that they don't all "just work" (since you have to do "minor" things to make some of them work), so we might change the title in response to that, etc.

**Pull request merged**
