### PR TITLE
Add semantic newlines for docs in "Common Tasks"

### PR DESCRIPTION
**Pull request by pierwill**
Just some housekeeping.

Background for the term "semantic newline" [here](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

(Happy to rebase into one commit as well.)

### CODE REVIEW

**Comment by unman** [comment]
On Sun, Aug 18, 2019 at 10:50:30AM -0700, pierwill wrote:
> Just some housekeeping.
> 
> Background for the term "semantic newline" [here](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/QubesOS/qubes-doc/pull/850
> 
> -- Commit Summary --
> 
>   * Add semantic newlines for blockdevices.md
>   * Add semantic newlines for copy-paste.md
>   * Add semantic newlines for copying-files.md
>   * Add semantic newlines for device-handling.md
>   * Add semantic newlines for disposablevm.md
>   * Add semantic newlines for full-screen-mode.md
>   * Add semantic newlines for optical-discs.md
>   * Add semantic newlines for pci-devices.md
>   * Add semantic newlines for software-update-dom0.md
>   * Add semantic newlines for software-update-vm.md
>   * Add semantic newlines for usb-devices-md
> 
> -- File Changes --
> 
>     M user/common-tasks/block-devices.md (35)
>     M user/common-tasks/copy-paste.md (30)
>     M user/common-tasks/copying-files.md (13)
>     M user/common-tasks/device-handling.md (61)
>     M user/common-tasks/disposablevm.md (6)
>     M user/common-tasks/full-screen-mode.md (23)
>     M user/common-tasks/optical-discs.md (5)
>     M user/common-tasks/pci-devices.md (37)
>     M user/common-tasks/software-update-dom0.md (41)
>     M user/common-tasks/software-update-vm.md (3)
>     M user/common-tasks/usb-devices.md (20)
> 
> -- Patch Links --
> 
> https://github.com/QubesOS/qubes-doc/pull/850.patch
> https://github.com/QubesOS/qubes-doc/pull/850.diff
> 

When did this become the style?
I thought it was agreed that we would use newline at the end of each
sentence, and only there.

**Comment by pierwill** [comment]
My changes here were pretty strictly limited to full-stopped sentences, I think.

But we might consider allowing, for instance, newlines after colons in long sentences. Something to think about...

**Comment by pierwill** [comment]
Also :smile:
> I thought it was agreed that we would use newline at the end of each
> sentence, and only there.

**Comment by andrewdavidwong** [comment]
> When did this become the style?
> I thought it was agreed that we would use newline at the end of each
sentence, and only there.

Isn't that what this patch does?

**Comment by unman** [comment]
On Mon, Aug 19, 2019 at 10:43:55AM -0700, pierwill wrote:
> Also :smile:
> > I thought it was agreed that we would use newline at the end of each
> > sentence, and only there.
> 

There's a difference between conventions in my email and conventions in
qubes-docs.

**Comment by unman** [comment]
On Mon, Aug 19, 2019 at 10:41:59AM -0700, pierwill wrote:
> My changes here were pretty strictly limited to full-stopped sentences, I think.
> 
> But we might consider allowing, for instance, newlines after colons in long sentences. Something to think about...
> 

Fantastic job.
But they aren't semantic newlines, and it would be better not to use the term, (unless we change convention)

**Pull request merged**
