### PR TITLE
Fix for issue #1169

### PR DESCRIPTION
**Pull request by unman**
Closes QubesOS/qubes-issues#1169 …

markdown didn't show command line options correctly.
Took opportunity to fix some typos and layout issues.

### CODE REVIEW

**Comment by marmarek** [comment]
Those files are generated from qubes-core-admin/doc,
qubes-core-admin-linux/doc, and qubes-core-agent-linux/doc. So all typos
fixed here will be lost on next update. We use `pandoc` for that
conversion, with some semi-manual post processing (like
adding/preserving frontmatter header).
Can you provide script (sed?) fixing the original issue here? We could
add it to conversion script (which exists currently only in my
`.bash_history`...). Since it's getting more than one-liner we should
write the conversion script somewhere (`qubesos.github.io/_utils` seems
to be the right place).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
@marmarek 
Hadn't realised that. No problem. I'll update the typos etc in the source.
I'll tidy up the script I used - awk ok? - try to minimise manual stuff and post it later.

**Comment by marmarek** [comment]
> awk ok?

Yes.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
@marmarek 
Something like this?
```
#!/usr/bin/awk -f
/---/ { print;next }
/SYNOPSIS/ { x=NR }
{if ( x>0 && NR >= x+3) {
if (/^$/){
x=0
}
else{
gsub(/\\/,"");print "`"$0"`  ";
next
}
}
}
/-{2}/ { gsub(/-{2}/,"\\-\\-"); print;next }
{ gsub(/>\\/,">   "); print }
```

**Comment by marmarek** [comment]
Yes, somethink like this :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
What is the status of this issue?

**Comment by axon-qubes** [comment]
This pull request appears to have been inactive for a long time and received no response to the recent query about its current status, so I'm closing it for now. If anyone thinks it should be reopened, please don't hesitate to let us know.

**Pull request closed without merging**
