### PR TITLE
explain how to publish the key

### PR DESCRIPTION
**Pull request by niccokunzmann**
Problem: The key needs to be published in order for the
  signature-checker to work. (my guess)
Solution: Add a section about uploading the key to a server.

### CODE REVIEW

**Comment by tasket** [comment]
You may also want to mention associating the key to your Github account (after uploading to keyserver step) as I think that is part of the checking process.

**Comment by marmarek** [comment]
> You may also want to mention associating the key to your Github account (after uploading to keyserver step) as I think that is part of the checking process.

Currently not (we use trust-on-first-use approach here), but it is used for "Verified" badge, which is nice :)
We may add such check in the future.

As for actual command - it might be a good idea to specify keyserver too, because in some systems there is no default specified.

**Comment by niccokunzmann** [comment]
@andrewdavidwong I think, I addressed the key server.

**Comment by niccokunzmann** [comment]
@tasket Do you have a link in mind? I only found one for uploading the private key which might not be what is intended.

**Comment by tasket** [comment]
@niccokunzmann For github the place for adding your Public key is here:
https://github.com/settings/keys

The `New GPG key` button will let you paste your Public key.

**Pull request merged**
