### PR TITLE
Fix qubes-os.org formatting problems

### PR DESCRIPTION
**Pull request by ttasket**
Some indentation and line spacing are mangling code blocks when displayed with the qubes-os.org stylesheet. Trying to correct...
In "Spaces" mode, I tried to get the editor to insert spaces instead of tabs, but it was converting my spaces into tabs :(
I also moved the warning about NM to the NM section.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Looks like we were working on this simultaneously. Can you try refreshing the live page to see if it looks ok now?

**Comment by andrewdavidwong** [comment]
(See https://github.com/QubesOS/qubes-doc/pull/161#issuecomment-223911222. Tabs vs. spaces is not the problem.)

**Comment by ttasket** [comment]
On 06/06/2016 05:42 AM, Andrew David Wong wrote:
>
> Looks like we were working on this simultaneously. Can you try 
> refreshing the live page to see if it looks ok now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/QubesOS/qubes-doc/pull/163#issuecomment-223913158>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/ANrHkZd0NVINv1rZONQoVPJSM2JV1mRiks5qI-uZgaJpZM4Iutrx>.
>

Looks good now.. thanks!

**Comment by andrewdavidwong** [comment]
Ok, great!

**Pull request closed without merging**
