### PR TITLE
Sentence case for titles

### PR DESCRIPTION
**Pull request by unman**
This is application of sentence case across all md files.
It addresses QubesOS/qubes-issues#6769
Some titles will need to be fixed, because the change is fairly crude: e.g. abbreviations have been lowercased- `Vm`, `api` , `ux`

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
> This is application of sentence case across all md files.
> It addresses [QubesOS/qubes-issues#6769](https://github.com/QubesOS/qubes-issues/issues/6769)

Thanks, @unman!

> Some titles will need to be fixed, because the change is fairly crude: e.g. abbreviations have been lowercased- `Vm`, `api` , `ux`

I've taken a pass to fix the remaining capitalization issues and update a few terms (e.g., `VM` -> `qube`).

**Comment by unman** [comment]
On Fri, Jul 09, 2021 at 05:17:22AM -0700, Andrew David Wong wrote:
> > This is application of sentence case across all md files.
> > It addresses [QubesOS/qubes-issues#6769](https://github.com/QubesOS/qubes-issues/issues/6769)
> 
> Thanks, @unman!
> 
> > Some titles will need to be fixed, because the change is fairly crude: e.g. abbreviations have been lowercased- `Vm`, `api` , `ux`
> 
> I've taken a pass to fix the remaining capitalization issues and update a few terms (e.g., `VM` -> `qube`).
> 

I'll cast an eye over them too.

**Comment by andrewdavidwong** [comment]
CI spell check results look good:

```
The following new unknown spellings were introduced:
    +Qfileexchgd
In addition, the following suspicious spellings were eliminated:
    -Configs
    -qfileexchgd
The introduced suspects in context are:
./_doc/developer/services/qfileexchgd.md:7:- /doc/Qfileexchgd/
./_doc/developer/services/qfileexchgd.md:8:- /wiki/Qfileexchgd/
./_doc/developer/services/qfileexchgd.md:10:title: Qfileexchgd (deprecated)
If these are false-positives, simply commit as is and they will
be ignored in the future.
```

These are expected.

**Comment by andrewdavidwong** [comment]
@unman, mind if I merge this now, or are you still looking it over?

**Comment by unman** [comment]
On Fri, Jul 09, 2021 at 07:35:08AM -0700, Andrew David Wong wrote:
> @unman, mind if I merge this now, or are you still looking it over?
> 

I doubt I will do it tonight, so merge it as is, and I'll check in the
morning for any minor issues.

**Comment by unman** [comment]
On review, I think you've caught every case.﻿
Ready to go

**Comment by andrewdavidwong** [comment]
> On review, I think you've caught every case.﻿
> Ready to go

Thanks for checking!

**Pull request merged**
