### PR TITLE
Fix misformating in Split GPG doc

### PR DESCRIPTION
**Pull request by haplo**
An error was introduced in pull request #717.

qubes doc split gpg misformat

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
This is because the `<` appears at the beginning of a line. As long as it's not the first character in a line, it'll be fine. For example, this would be another way to fix it:

```
you have a private key that already has a passphrase set use `gpg2
--edit-key <key_id>`, then `passwd` to set an empty passphrase. Be aware that
```

**Comment by haplo** [comment]
Thank you @andrewdavidwong , I wasn't sure so I went with the safe option.

**Comment by andrewdavidwong** [comment]
You should always check your changes by [serving the site on your local machine](https://github.com/QubesOS/qubesos.github.io#instructions) before submitting.

**Comment by haplo** [comment]
Thank you Andrew, I will run and check it next time for sure.

**Pull request merged**
