### PR TITLE
4.0 updates for software-update-vm

### PR DESCRIPTION
**Pull request by awokd**
From info in https://github.com/QubesOS/qubes-issues/issues/3495

### CODE REVIEW

**Comment by awokd** [comment]
My main goal with this update effort is to split out and add 4.0 content. Secondary is to brush up stuff I see or you guys point out is outdated on 3.2. I'm not really trying to refactor existing documentation (except where required, such as the dom0 tools pages).
I can see, though, how now would be a good time to refactor it though since we're going to touch a good portion of the documents. For a happy medium, could you (@andrewdavidwong ) handle that portion of it?

**Comment by andrewdavidwong** [comment]
> My main goal with this update effort is to split out and add 4.0 content. Secondary is to brush up stuff I see or you guys point out is outdated on 3.2. I'm not really trying to refactor existing documentation (except where required, such as the dom0 tools pages).
I can see, though, how now would be a good time to refactor it though since we're going to touch a good portion of the documents. For a happy medium, could you (@andrewdavidwong ) handle that portion of it?

Yes, absolutely! That's totally reasonable.

**Comment by awokd** [comment]
I see some of my older PRs (like this one) sitting in https://github.com/QubesOS/qubes-doc/pulls. Not trying to rush you, but am checking in to see if there's something I'm supposed to be doing with them, or if the ball is in your court?

**Comment by andrewdavidwong** [comment]
> I see some of my older PRs (like this one) sitting in https://github.com/QubesOS/qubes-doc/pulls. Not trying to rush you, but am checking in to see if there's something I'm supposed to be doing with them, or if the ball is in your court?

You can tell by looking at the Assignee(s) for each PR. Right now, all of your open PRs are assigned to Marek (because they're awaiting his review), so no action is required on your part.

**Comment by awokd** [comment]
Updated.

**Pull request merged**
